<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Background and Basic Concepts – Survival analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./survivor.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./background.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background and Basic Concepts</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Survival analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background and Basic Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survivor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimating survivor functions: life-tables and Kaplan-Meier</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parametric one-sample models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twosample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Two Sample Comparisons</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Accelerated Failure Time (AFT) Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proportionalhazards.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-is-survival-analysis" id="toc-what-is-survival-analysis" class="nav-link active" data-scroll-target="#what-is-survival-analysis"><span class="header-section-number">1.1</span> What is survival analysis?</a></li>
  <li><a href="#terminology-survival-times-and-failure-times" id="toc-terminology-survival-times-and-failure-times" class="nav-link" data-scroll-target="#terminology-survival-times-and-failure-times"><span class="header-section-number">1.2</span> Terminology: survival times and failure times</a></li>
  <li><a href="#censoring" id="toc-censoring" class="nav-link" data-scroll-target="#censoring"><span class="header-section-number">1.3</span> Censoring</a>
  <ul class="collapse">
  <li><a href="#types-of-censoring" id="toc-types-of-censoring" class="nav-link" data-scroll-target="#types-of-censoring"><span class="header-section-number">1.3.1</span> Types of Censoring</a></li>
  <li><a href="#informative-and-non-informative-censoring" id="toc-informative-and-non-informative-censoring" class="nav-link" data-scroll-target="#informative-and-non-informative-censoring"><span class="header-section-number">1.3.2</span> Informative and Non-Informative Censoring</a></li>
  </ul></li>
  <li><a href="#survival-time-distributions-key-definitions" id="toc-survival-time-distributions-key-definitions" class="nav-link" data-scroll-target="#survival-time-distributions-key-definitions"><span class="header-section-number">1.4</span> Survival time distributions: key definitions</a>
  <ul class="collapse">
  <li><a href="#survivor-function" id="toc-survivor-function" class="nav-link" data-scroll-target="#survivor-function"><span class="header-section-number">1.4.1</span> Survivor Function</a></li>
  <li><a href="#hazard-function" id="toc-hazard-function" class="nav-link" data-scroll-target="#hazard-function"><span class="header-section-number">1.4.2</span> Hazard function</a></li>
  <li><a href="#relationships-between-hazard-survivor-and-density-functions" id="toc-relationships-between-hazard-survivor-and-density-functions" class="nav-link" data-scroll-target="#relationships-between-hazard-survivor-and-density-functions"><span class="header-section-number">1.4.3</span> Relationships between hazard, survivor and density functions</a></li>
  </ul></li>
  <li><a href="#standard-survival-time-distributions" id="toc-standard-survival-time-distributions" class="nav-link" data-scroll-target="#standard-survival-time-distributions"><span class="header-section-number">1.5</span> Standard survival time distributions</a>
  <ul class="collapse">
  <li><a href="#sec-exponential" id="toc-sec-exponential" class="nav-link" data-scroll-target="#sec-exponential"><span class="header-section-number">1.5.1</span> The exponential distribution</a></li>
  <li><a href="#sec-weibull" id="toc-sec-weibull" class="nav-link" data-scroll-target="#sec-weibull"><span class="header-section-number">1.5.2</span> The Weibull Distribution</a></li>
  </ul></li>
  <li><a href="#an-example-dataset" id="toc-an-example-dataset" class="nav-link" data-scroll-target="#an-example-dataset"><span class="header-section-number">1.6</span> An example dataset</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background and Basic Concepts</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aims for this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter, the aim is to understand</p>
<ol type="1">
<li><p>what survival analysis is; what sort of data we analyse in survival analysis;</p></li>
<li><p>the concept of “censoring” and why this complicates analysing survival data;</p></li>
<li><p>the concept of the “hazard function” and its role in modelling survival data.</p></li>
</ol>
</div>
</div>
<section id="what-is-survival-analysis" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="what-is-survival-analysis"><span class="header-section-number">1.1</span> What is survival analysis?</h2>
<p>In survival analysis, we analyse <strong>time-to-event data</strong>: how long we have to wait for a particular event to occur. In medical statistics, the interest is often in how long a patient will survive on a particular treatment (e.g.&nbsp;a treatment for cancer), and so the “event” would be the death of a patient: in a survival analysis we analyse how long the patients live. We may have other explanatory variables for each observation, e.g.&nbsp;the age of each patient, and what treatment they received.</p>
<p>A simple illustration of the type of data we consider in survival analysis is in <a href="#fig-exampleVis" class="quarto-xref">Figure&nbsp;<span>1.1</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exampleVis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exampleVis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="background_files/figure-html/fig-exampleVis-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exampleVis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: A visualisation of a simple example dataset in survival analysis. We have two groups of observations, and for each observation in each group, we observe a “survival time”: how long it takes for some event to occur. The interest may be in whether the mean survival time is different between the two groups.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In clinical trials, patients usually enter the trial at different times over some period, and so don’t all start treatment at the same time. We’ll ignore this in this module, and suppose observation of all patients starts at time 0 (or that the data have already been converted into this format).</p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://doi.org/10.1038/bjc.2017.179">Koshiaris et al (2017)</a> investigated how quitting smoking affects survival for patients with different cancers. They studied a group of patients who were all smokers at the time of their cancer diagnosis and survived for at least one year. For different cancer types (e.g.&nbsp;lung cancer), they then studied the survival times of those patients who quit smoking within their first year, and those patients who continued smoking, to see if patients tended to live longer if they gave up smoking.</p>
</div>
</div>
</section>
<section id="terminology-survival-times-and-failure-times" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="terminology-survival-times-and-failure-times"><span class="header-section-number">1.2</span> Terminology: survival times and failure times</h2>
<p>In survival analysis, we may refer to either the <strong>survival time</strong> or the <strong>failure time</strong>:</p>
<ul>
<li>failure time: the time at which some event occurs;</li>
<li>survival time: (a duration) how long we wait until the failure event.</li>
</ul>
<p>As we start counting from time zero, numerically, failure time and survival time are the same, and the two terms can be used interchangeably.</p>
<p>“Survival time” is more commonly used in medical statistics, as we are often studying treatments to improve patient survival. “Failure time” is more commonly used on non-medical applications, e.g.&nbsp;applications in engineering where we may study how long an time operates until a fault develops: the item “fails”.</p>
</section>
<section id="censoring" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="censoring"><span class="header-section-number">1.3</span> Censoring</h2>
<p>In a clinical trial, a patient may withdraw from the trial for reasons unrelated to their treatment, or they reach the end of the trial before the event has occurred (e.g.&nbsp;they are still alive at the end of the trial). This results in a <strong>censored</strong> observation: instead of observing the survival time, we just know that it must exceed some particular value. An illustration is given in <a href="#fig-TimeCensoring" class="quarto-xref">Figure&nbsp;<span>1.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-TimeCensoring" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-TimeCensoring-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="background_files/figure-html/fig-TimeCensoring-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-TimeCensoring-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Illustration of censoring. We suppose a study has been run for 6 months. For observation number 3, the patient was still alive after 2 months, but dropped out of the study. For observation number 5, the patient was still alive at the end of the study. For these two observations, rather than observing the failure times, we just know that the failure times were <em>greater than</em> 2 months and 6 months respectively.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Censoring is an important distinctive feature of survival analysis, and the reason we can’t use other methods you may be familiar (e.g.&nbsp;linear modelling) directly. In <a href="#fig-TimeCensoring" class="quarto-xref">Figure&nbsp;<span>1.2</span></a>, the observations we have to analyse are <span class="math display">\[
t_1=0.5,\,t_2=4.1,\,t_4=2.75\quad \mbox{ and } \quad t_3&gt;2, \,t_5&gt;6
\]</span> How, for example, would you estimate the mean survival time in this case?</p>
</div>
</div>
<section id="types-of-censoring" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="types-of-censoring"><span class="header-section-number">1.3.1</span> Types of Censoring</h3>
<p>There are several forms of censoring:</p>
<ul>
<li><p><strong>Right Censoring</strong> — the survival time exceeds some value. The event (e.g.&nbsp;death) hadn’t occurred when the individual was lost to the study or the study ended;</p></li>
<li><p><strong>Left Censoring</strong> — the survival time is less than some value. This might occur if subjects are only observed after a fixed period of time. Here, we would know that survival time is less than the period of observation. Another example is when the survival time is the time to recurrence of a tumour, where the presence of such a tumour is only observable during surgery.</p></li>
<li><p><strong>Interval Censoring</strong> — the survival time is within some range of values. This might occur if individuals are observed at a sequence of fixed appointment times.</p></li>
<li><p><strong>Type I Censoring</strong> — identical starting points and subjects are observed for a fixed time. The number of censored observations is then random.</p></li>
<li><p><strong>Type II Censoring</strong> — the trial finishes after a certain number of events. Here we do not specify the end of the trial in terms of time but in terms of the number of events. This type of censoring is less common in medical studies but is widely used in electronic component testing and reliability studies. Here the number of censored observations is not random but is fixed in advance.</p></li>
</ul>
<p>We typically consider Right censoring.</p>
</section>
<section id="informative-and-non-informative-censoring" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="informative-and-non-informative-censoring"><span class="header-section-number">1.3.2</span> Informative and Non-Informative Censoring</h3>
<p>For all the techniques presented in this module we will assume that the censoring is random (or non-informative). This means that the censoring time is <strong>statistically independent</strong> of the failure time. This excludes situations whereby people are censored in a clinical trial if they suddenly become seriously ill and, as a consequence, are removed from the trial. Here censoring suggests that an individual is near death. It also excludes situations where they are censored/lost if they become/feel better. Here censoring would suggest that an individual is a long way from death. Examples such as these are known as informative sampling as the act of censoring gives extra information about the survival time.</p>
<p>Analysing informatively censored data is very difficult. If such informative censoring is present then the methods described here would often lead to biased estimates. In any survival analysis one should think carefully about whether the censoring is informative.</p>
</section>
</section>
<section id="survival-time-distributions-key-definitions" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="survival-time-distributions-key-definitions"><span class="header-section-number">1.4</span> Survival time distributions: key definitions</h2>
<p>Suppose we have a homogeneous population of individuals, and the survival time of each individual is a continuous random variable <span class="math inline">\(T&gt;0\)</span> with probability density <span class="math inline">\(f(t)\)</span> and distribution function <span class="math inline">\(F(t)\)</span>: <span class="math display">\[\begin{align}
F(t) = P(T \leq t) \quad &amp; \textrm{and} \quad f(t) = F'(t) \qquad (\textrm{so } F(t) = \int_0^t f(u) du).
\end{align}\]</span></p>
<p>We wish to estimate the distribution of <span class="math inline">\(T\)</span> given, possibly censored, survival data. We first need to define some other functions which are all inter-related.</p>
<section id="survivor-function" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="survivor-function"><span class="header-section-number">1.4.1</span> Survivor Function</h3>
<p>We define the <strong>survivor function</strong> <span class="math inline">\(S(t)\)</span> as</p>
<p><span class="math display">\[
S(t) = P(T \geq t).
\]</span></p>
<p>For a continuous random variable <span class="math inline">\(T\)</span>, we have <span class="math inline">\(P(T=t)=0\)</span>, and so <span class="math display">\[
S(t) = 1 - F(t) = \int_t^\infty f(u) du.
\]</span></p>
<p>We also have <span class="math display">\[f(t) = -S'(t).\]</span></p>
<p>We tend to work with the survivor function <span class="math inline">\(S(t)\)</span> rather than the distribution function <span class="math inline">\(F(t)\)</span>, as <span class="math inline">\(S(t)\)</span> matches the form of right-censored observations where we observe a survival time <span class="math inline">\(T\)</span> exceeding some value <span class="math inline">\(t\)</span>.</p>
</section>
<section id="hazard-function" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="hazard-function"><span class="header-section-number">1.4.2</span> Hazard function</h3>
<p>We often model the lifetime through the hazard function, <span class="math inline">\(h(t)\)</span>, which measures the risk or proneness to death at time <span class="math inline">\(t\)</span>, given survival up to time <span class="math inline">\(t\)</span>. The hazard function represents the instantaneous death rate for an individual surviving to time <span class="math inline">\(t\)</span>. <span class="math display">\[
h(t) := \lim_{h \rightarrow 0} \frac{P(t \leq T&lt;t+h|T \geq t)}{h}.
\]</span></p>
<p>By the definition of conditional probability, we find that <span class="math display">\[\begin{align}
h(t) &amp;= \lim_{h \rightarrow 0} \frac{P(t\leq T&lt;t+h, T \geq t)}{P(T \geq t) h} \nonumber \\
&amp;= \lim_{h \rightarrow 0} \frac{P(t&lt;T&lt;t+h)}{P(T \geq t) h} \nonumber \\
&amp;= \left\{ \lim_{h \rightarrow 0} \frac{P(t&lt;T&lt;t+h)}{h}\right\} \frac{1}{P(T \geq t)} \nonumber \\
&amp;= \left\{ \lim_{h \rightarrow 0} \frac{F(t+h)-F(t)}{h}\right\} \frac{1}{P(T \geq t)} \nonumber \\
&amp;= \frac{F'(t)}{S(t)}=\frac{f(t)}{S(t)}.
\end{align}\]</span>{#eq-relations}</p>
<p>The Cumulative (or “Integrated”) Hazard Function <span class="math inline">\(H(t)\)</span> is defined as <span class="math display">\[
H(t) := \int_0^t h(u) du = -\log{S(t)}.
\]</span></p>
</section>
<section id="relationships-between-hazard-survivor-and-density-functions" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="relationships-between-hazard-survivor-and-density-functions"><span class="header-section-number">1.4.3</span> Relationships between hazard, survivor and density functions</h3>
<p>If we specify any one of these three functions, the other two are determined.</p>
<p>Substituting <span class="math inline">\(f(t) = -S'(t)\)</span>, we have <span class="math display">\[
h(t) =\frac{f(t)}{S(t)}= \frac{-S'(t)}{S(t)}
= - \frac{d}{dt} \log{S(t)}.
\]</span></p>
<p>Hence we can obtain the survivor function from the hazard function: <span class="math display">\[
S(t) = \exp \left\{ -\int_0^t h(u) du \right\} = \exp \{ -H(t) \}.
\]</span> The density function can also be derived from the hazard function, as <span class="math inline">\(f(t) = -S'(t)\)</span>: <span class="math display">\[
f(t) =-\frac{d}{dt}S(t)= -\frac{d}{dt}\exp \left\{ -\int_0^t h(u) du \right\}= h(t) \exp \{ -H(t) \}.
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The hazard function is a fundamental concept in survival analysis: make sure you understand the definition and these relationships well! The hazard function has an important role in modelling survival data, as it can be more intuitive to consider how a hazard function changes over time. We sometimes assess the suitability of a particular distribution/model for survival data on the basis of whether the behaviour of the hazard function is plausible.</p>
</div>
</div>
</section>
</section>
<section id="standard-survival-time-distributions" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="standard-survival-time-distributions"><span class="header-section-number">1.5</span> Standard survival time distributions</h2>
<p>Various distributions can be used for modelling survival data. We will start by specifying the hazard function, and derive the distribution from that.</p>
<section id="sec-exponential" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="sec-exponential"><span class="header-section-number">1.5.1</span> The exponential distribution</h3>
<p>Suppose, for a random variable <span class="math inline">\(T\)</span> with <span class="math inline">\(T\ge 0\)</span>, we assume a constant hazard function <span class="math display">\[
h(t) = \lambda,
\]</span> for all <span class="math inline">\(t\ge 0\)</span>. This gives a cumulative hazard function <span class="math display">\[
H(t) = \int_0^t \lambda du = \lambda t.
\]</span> We then obtain</p>
<p><span class="math display">\[\begin{align}
S(t)&amp;= e^{-\lambda t}  \\
f(t) &amp; = \lambda e^{-\lambda t} \\
F(t) &amp;=1-e^{-\lambda t}
\end{align}\]</span></p>
<p>and we can see that <span class="math inline">\(T\)</span> has the exponential distribution with rate <span class="math inline">\(\lambda\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>You may recall the “lack of memory” property for exponential random variables: <span class="math display">\[
P(T\ge t+s|T\ge s) = P(T\ge t),
\]</span> e.g.&nbsp;a patient surviving for an <em>additional</em> <span class="math inline">\(t\)</span> units of time does not depend on how long the patient has survived up to that point (the value of <span class="math inline">\(s\)</span> has no effect) on the probability. This is one way to understand what constant hazard means.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Whilst the exponential distribution is the simplest distribution for modelling survival data, it is not always appropriate, precisely because of the constant hazard assumption: the assumption that the risk of death never changes, regardless of how old one gets.</p>
</div>
</div>
</section>
<section id="sec-weibull" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="sec-weibull"><span class="header-section-number">1.5.2</span> The Weibull Distribution</h3>
<p>Consider a hazard function of the form <span class="math display">\[
h(t) = \lambda \gamma (\lambda t) ^ {\gamma-1},
\]</span> for <span class="math inline">\(t\ge 0\)</span>. The hazard can now change over time. Note that</p>
<ul>
<li><p><span class="math inline">\(\gamma &gt; 1\)</span> means the hazard is increasing over time;</p></li>
<li><p><span class="math inline">\(\gamma = 1\)</span> means the hazard is constant and we have an exponential distribution;</p></li>
<li><p><span class="math inline">\(\gamma &lt; 1\)</span> means the hazard is decreasing over time.</p></li>
</ul>
<p>This gives a cumulative hazard function <span class="math display">\[
H(t)=\int_0^t \lambda \gamma (\lambda u) ^ {\gamma-1}du = (\lambda t)^\gamma,
\]</span> and so</p>
<p><span class="math display">\[\begin{align}
S(t) &amp;= \exp\left[ -(\lambda t) ^ \gamma \right]  \\
f(t) &amp;= \lambda \gamma (\lambda t) ^ {\gamma-1} \exp\left[ -(\lambda t) ^ \gamma \right]\\
F(t) &amp; 1 - \exp\left[ -(\lambda t) ^ \gamma \right].
\end{align}\]</span></p>
<p>This is another standard distribution: the Weibull distribution. We write <span class="math inline">\(T \sim Weibull(\lambda, \gamma)\)</span>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Textbooks and software do not all parametrise the Weibull distribution the same way! The parametrisation above is the one used in the <code>survreg</code> function in R (we will use this key function extensively in later Chapters). But, confusingly, the <code>dweibull</code> function in R writes the density <span class="math inline">\(f(t)\)</span> as <span class="math display">\[
f(t) = (a/\sigma) ( t/\sigma) ^ {a-1} \exp\left[ -( t/\sigma) ^ a \right],
\]</span> with a “scale” parameter <span class="math inline">\(\sigma\)</span> corresponding to <span class="math inline">\(1/\lambda\)</span>.</p>
</div>
</div>
</section>
</section>
<section id="an-example-dataset" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="an-example-dataset"><span class="header-section-number">1.6</span> An example dataset</h2>
<p>The <code>survival</code> package in R includes example datasets. These are useful for studying and experimenting with particular methods. One dataset we will use is the North Central Cancer Treatment Group lung cancer data, obtained using <code>survival::lung</code>. For more details about the data, type <code>?survival::lung</code> in R.</p>
<p>We will simplify the data a little, extracting two columns only and recoding status (0 = censored, 1 = died):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>lungData <span class="ot">&lt;-</span> survival<span class="sc">::</span>lung <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(time, status) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span> (<span class="at">status =</span> status <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lungData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time status
1  306      1
2  455      1
3 1010      0
4  210      1
5  883      1
6 1022      0</code></pre>
</div>
</div>
<p>In this extract, patient 1 died after 306 days of observation, patient 3 was still alive after 1010 days of observation, and was then no longer in the study.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Acknowledgements">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Acknowledgements</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./survivor.html" class="pagination-link" aria-label="Estimating survivor functions: life-tables and Kaplan-Meier">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimating survivor functions: life-tables and Kaplan-Meier</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>