<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Parametric one-sample models – Survival analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./twosample.html" rel="next">
<link href="./survivor.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./parametric.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parametric one-sample models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Survival analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background and Basic Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survivor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimating survivor functions: life-tables and Kaplan-Meier</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parametric.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parametric one-sample models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twosample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Two Sample Comparisons</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Accelerated Failure Time (AFT) Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proportionalhazards.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#exponential-models" id="toc-exponential-models" class="nav-link active" data-scroll-target="#exponential-models"><span class="header-section-number">3.1</span> Exponential models</a>
  <ul class="collapse">
  <li><a href="#uncensored-data" id="toc-uncensored-data" class="nav-link" data-scroll-target="#uncensored-data"><span class="header-section-number">3.1.1</span> Uncensored Data</a></li>
  <li><a href="#sec-censExp" id="toc-sec-censExp" class="nav-link" data-scroll-target="#sec-censExp"><span class="header-section-number">3.1.2</span> Censored Data</a></li>
  <li><a href="#varfuncmle" id="toc-varfuncmle" class="nav-link" data-scroll-target="#varfuncmle"><span class="header-section-number">3.1.3</span> Interest in Other Parameters</a></li>
  <li><a href="#an-example-lung-cancer-survival" id="toc-an-example-lung-cancer-survival" class="nav-link" data-scroll-target="#an-example-lung-cancer-survival"><span class="header-section-number">3.1.4</span> An Example: Lung Cancer Survival</a></li>
  <li><a href="#allowing-random-censoring-only-examinable-in-mps438" id="toc-allowing-random-censoring-only-examinable-in-mps438" class="nav-link" data-scroll-target="#allowing-random-censoring-only-examinable-in-mps438"><span class="header-section-number">3.1.5</span> Allowing Random Censoring (only examinable in MPS438)</a></li>
  </ul></li>
  <li><a href="#survreg" id="toc-survreg" class="nav-link" data-scroll-target="#survreg"><span class="header-section-number">3.2</span> Fitting Parametric models in R</a>
  <ul class="collapse">
  <li><a href="#fitting-an-exponential-model-to-the-lung-cancer-data" id="toc-fitting-an-exponential-model-to-the-lung-cancer-data" class="nav-link" data-scroll-target="#fitting-an-exponential-model-to-the-lung-cancer-data"><span class="header-section-number">3.2.1</span> Fitting an Exponential model to the lung cancer data</a></li>
  <li><a href="#fitting-a-weibull-model-to-the-tumour-remission-data" id="toc-fitting-a-weibull-model-to-the-tumour-remission-data" class="nav-link" data-scroll-target="#fitting-a-weibull-model-to-the-tumour-remission-data"><span class="header-section-number">3.2.2</span> Fitting a Weibull model to the tumour remission data</a></li>
  <li><a href="#checking-goodness-of-fit" id="toc-checking-goodness-of-fit" class="nav-link" data-scroll-target="#checking-goodness-of-fit"><span class="header-section-number">3.2.3</span> Checking goodness of fit</a></li>
  </ul></li>
  <li><a href="#tasks" id="toc-tasks" class="nav-link" data-scroll-target="#tasks"><span class="header-section-number">3.3</span> Tasks</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parametric one-sample models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aims for this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter, the aim is to fit a standard parametric distribution (such as the exponential distribution) to survival data. We will</p>
<ol type="1">
<li><p>use likelihood methods to fit the exponential distribution to data;</p></li>
<li><p>incorporate censored data by specifying the likelihood function appropriately;</p></li>
<li><p>use R to fit other models (e.g.&nbsp;Weibull; lognormal) using the <code>survreg()</code> function.</p></li>
</ol>
</div>
</div>
<p>Suppose we have a non-negative failure time <span class="math inline">\(T\)</span> with p.d.f. <span class="math inline">\(f(t)\)</span>; distribution function <span class="math inline">\(F(t)\)</span>; survival function <span class="math inline">\(S(t)=1 - F(t)\)</span> ; and hazard function <span class="math inline">\(h(t)\)</span>. Typically the pdf depends on an unknown parameter <span class="math inline">\(\theta\)</span> that needs to be estimated from the data. There are many methods of estimation but we concentrate on maximum likelihood estimation (m.l.e.) and then perform tests/inference relying on its nice asymptotic (large sample) properties.</p>
<p>To find the mle, we first find the likelihood <span class="math inline">\(L(\theta)\)</span> of a parameter <span class="math inline">\(\theta\)</span> for data <span class="math inline">\(x_1, \ldots ,x_n\)</span>. We can now maximize <span class="math inline">\(L(\theta)\)</span> wrt <span class="math inline">\(\theta\)</span> to find the maximum likelihood estimate of <span class="math inline">\(\theta\)</span>. To do this we usually maximise the log-likelihood as this is generally simpler to work with.</p>
<section id="exponential-models" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="exponential-models"><span class="header-section-number">3.1</span> Exponential models</h2>
<p>Refer to <a href="background.html#sec-exponential" class="quarto-xref"><span>Section 1.5.1</span></a> for the density and survivor functions.</p>
<section id="uncensored-data" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="uncensored-data"><span class="header-section-number">3.1.1</span> Uncensored Data</h3>
<p>Suppose we observe (non-censored) failure times <span class="math inline">\(t_1,t_2, \ldots,t_n\)</span>, then <span class="math display">\[\begin{align}
L(\lambda;t_1,t_2,\ldots,t_n) &amp;= \prod_{i=1}^n f(t_i) = \lambda^n e^{-\lambda \sum_{i=1}^n t_i} \\
\log(L)= l(\lambda) &amp;= n \log(\lambda)-\lambda \sum_{i=1}^n t_i \\
\Rightarrow \hat{\lambda} = \frac{n}{\sum_{i=1}^n t_i}.
\end{align}\]</span> We can also find a confidence interval for <span class="math inline">\(\lambda\)</span> since <span class="math inline">\(Y = \sum_{i=1}^n T_i \sim \Gamma(n , \lambda)\)</span> and <span class="math display">\[Z= 2\lambda Y \sim \chi^2_{2n}.\]</span> Hence <span class="math display">\[P\left(\chi^2_{2n; \alpha/2} &lt; 2\lambda \sum_{i=1}^n T_i &lt; \chi^2_{2n; 1- \alpha/2}\right)= 1- \alpha,\]</span> and so a <span class="math inline">\(100(1-\alpha)\%\)</span> confidence interval for <span class="math inline">\(\lambda\)</span> is given by <span class="math display">\[
\left(\frac{\chi^2_{2n; \alpha/2}}{2 \sum_{i=1}^n t_i}, \frac{\chi^2_{2n; 1- \alpha/2}}{2 \sum_{i=1}^n t_i}  \right).
\]</span> Finally we can find the mle of <span class="math inline">\(S(t)\)</span> as <span class="math display">\[\hat{S}(t) = e^{-\hat{\lambda} t}\]</span></p>
</section>
<section id="sec-censExp" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="sec-censExp"><span class="header-section-number">3.1.2</span> Censored Data</h3>
<p>Now suppose that we have right censored data. Specifically, let us consider <span class="math inline">\(n\)</span> patients, with potential i.i.d. lifetimes <span class="math inline">\(T_i \sim Exp(\lambda)\)</span>. We observe either the lifetime <span class="math inline">\(t_i\)</span> or the fact that <span class="math inline">\(t_i&gt;c_i\)</span> for individual <span class="math inline">\(i\)</span>. The simplest case is to assume that the <span class="math inline">\(c_i\)</span> are fixed and known for all individuals, i.e.&nbsp;non-random. For individuals where we observe the failure time (where <span class="math inline">\(t_i \leq c_i\)</span>), the contribution of each individual to the likelihood is <span class="math display">\[f(t_i) = \lambda e^{-\lambda t_i}.\]</span> For individuals where we observe the right-censored value (where <span class="math inline">\(t_i &gt; c_i\)</span>), using the fact that <span class="math inline">\(P(T_i &gt; c_i) = S(c_i)\)</span>, the contribution to the likelihood is <span class="math display">\[S(c_i)=e^{-\lambda c_i}.\]</span> If we define <span class="math display">\[
\delta_i= \left\{ \begin{array}{ll} 1 &amp; \textrm{if } t_i \leq c_i \textrm{ (i.e. uncensored)} \\
                   0 &amp; \textrm{if } t_i &gt; c_i \textrm{ (i.e. censored)} \end{array} \right.
\]</span> then <span class="math display">\[
L(\lambda) = \prod_{i=1}^n  \left[f(t_i) \right]^{\delta_i} \left[ S(c_i)\right]^{1- \delta_i} =  \prod_{i=1}^n  \left[\lambda e^{-\lambda t_i} \right]^{\delta_i} \left[ e^{-\lambda c_i} \right]^{1- \delta_i}.
\]</span> It follows that <span class="math display">\[\begin{align}
l(\lambda) &amp;= \log{\lambda} \sum_{i=1}^n \delta_i  - \lambda \sum_{i=1}^n t_i\delta_i - \lambda \sum_{i=1}^n (1-\delta_i)c_i \\
\frac{\partial l}{\partial \lambda} &amp;= \frac{\sum_{i=1}^n \delta_i}{\lambda}  - \sum_{i=1}^n \left( t_i\delta_i + (1-\delta_i)c_i \right) \\
\Rightarrow \hat{\lambda} &amp;= \frac{\sum_{i=1}^n \delta_i}{\sum_{i=1}^n \left(  t_i\delta_i + (1-\delta_i)c_i \right)}.
\end{align}\]</span></p>
<p>We can use the asymptotic properties of maximum likelihood estimators to find confidence intervals for <span class="math inline">\(\hat{\lambda}\)</span>. We have <span class="math display">\[
\hat{\lambda} \xrightarrow{d} N \left( \lambda, I^{-1} \right),
\]</span> where <span class="math inline">\(I^{-1}=var(\hat{\lambda})\)</span> is the variance-covariance matrix of <span class="math inline">\(\hat{\lambda}\)</span>. If we use the Fisher information then <span class="math inline">\(I\)</span> is given by <span class="math display">\[
I = E \left[ - \frac{\partial^2 l}{\partial \lambda^2} \right].
\]</span> Now, in our case <span class="math display">\[\frac{\partial^2 l}{\partial \lambda^2} = -\frac{\sum \delta_i}{\lambda^2}\]</span> and (implicitly assuming that the <span class="math inline">\(c_i\)</span> are considered non-random) <span class="math display">\[\begin{align}
E[\delta_i] &amp;=1 P(T_i \leq c_i) + 0 P(T_i&gt;c_i) \\
&amp; = (1-e^{-\lambda c_i}).
\end{align}\]</span> Replacing <span class="math inline">\(\lambda\)</span> with <span class="math inline">\(\hat{\lambda}\)</span> we have that <span class="math display">\[
var(\hat{\lambda}) \approx \frac{\hat{\lambda}^2}{\sum_{i=1}^n (1-e^{-\hat{\lambda} c_i})}.
\]</span> Alternatively, we can use the observed information to specify <span class="math inline">\(I\)</span>. In this case we have <span class="math display">\[
I= - \frac{\partial^2 l}{\partial \lambda^2} \Bigr|_{\lambda = \hat \lambda}
\]</span> giving <span class="math display">\[
var(\hat{\lambda}) \approx \frac{\hat{\lambda}^2}{\sum_{i=1}^n \delta_i}.
\]</span> To find a <span class="math inline">\(100(1- \alpha)\%\)</span> confidence interval for <span class="math inline">\(\lambda\)</span> we use the fact that the distribution of <span class="math inline">\(\hat{\lambda}\)</span> is normal giving us the interval <span class="math display">\[
\hat{\lambda} \pm 1.96 \times \sqrt{var(\hat{\lambda})}
\]</span></p>
</section>
<section id="varfuncmle" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="varfuncmle"><span class="header-section-number">3.1.3</span> Interest in Other Parameters</h3>
<p>Our interest may be in other aspects, e.g.&nbsp;the mean lifetime <span class="math inline">\(\mu= E[T]=\lambda^{-1}\)</span>; or the age <span class="math inline">\(S_\alpha\)</span> beyond which <span class="math inline">\(100\alpha\%\)</span> survive. To estimate these we use the result that for any differentiable, monotonic function <span class="math inline">\(g(\lambda)\)</span>, we have <span class="math display">\[
var(g(\hat{\lambda})) \approx \{g'(\lambda)\}^2  \mid_{\lambda = \hat{\lambda}}var(\hat \lambda).
\]</span> Suppose we want to find the variance of the m.l.e of the mean lifetime <span class="math inline">\(var(\hat{\mu})\)</span>. Since <span class="math inline">\(\hat{\mu} = 1/\hat{\lambda}\)</span> we have <span class="math inline">\(g(\lambda) = 1/\lambda\)</span>. Using the fisher information we get that <span class="math display">\[
var(\hat{\mu}) \approx  \frac{\hat{\mu}^2}{\sum_{i=1}^n (1-e^{-\hat{\lambda} c_i})}.
\]</span> If using the observed information we replace <span class="math inline">\(\sum_{i=1}^n (1-e^{-\hat{\lambda} c_i})\)</span> with <span class="math inline">\(\sum_{i=1}^n \delta_i\)</span>. Suppose we want to find the variance of the estimator of the time beyond which <span class="math inline">\(100 \alpha\%\)</span> survive, <span class="math inline">\(var(\hat{S}_\alpha)\)</span>. We have <span class="math inline">\(\alpha = P(T \geq S_\alpha) = S(S_\alpha) = e^{-\lambda S_\alpha}\)</span> and so <span class="math display">\[\begin{align}
S_\alpha &amp;= - \lambda^{-1} \log \alpha  \\
\Rightarrow \hat{S}_\alpha &amp;= - \hat{\lambda}^{-1} \log \alpha
\end{align}\]</span> and to find the variance, <span class="math display">\[\begin{align}
var(\hat{S}_\alpha) &amp;= var(- \hat{\lambda}^{-1} \log \alpha)  \\
&amp;= \left[ -\log \alpha \right]^2  var(\hat{\lambda}^{-1}) .
\end{align}\]</span></p>
</section>
<section id="an-example-lung-cancer-survival" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="an-example-lung-cancer-survival"><span class="header-section-number">3.1.4</span> An Example: Lung Cancer Survival</h3>
<p>The survival times (in days) of 10 patients with advanced lung cancer are shown in <a href="#tbl-LCancer" class="quarto-xref">Table&nbsp;<span>3.1</span></a>. The study terminated after 90 days and any patient still alive at that point was no longer observed. Patients joined the study at different times.</p>
<div id="tbl-LCancer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-LCancer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: 90 day study of 10 patients with lung cancer
</figcaption>
<div aria-describedby="tbl-LCancer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Patient.no.</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">6</th>
<th style="text-align: center;">7</th>
<th style="text-align: center;">8</th>
<th style="text-align: center;">9</th>
<th style="text-align: center;">10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Entry time</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">61</td>
<td style="text-align: center;">69</td>
</tr>
<tr class="even">
<td style="text-align: left;">Max. possible <span class="math inline">\(c_i\)</span></td>
<td style="text-align: center;">81</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Survival time <span class="math inline">\(t_i\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(&gt;72\)</span></td>
<td style="text-align: center;">51</td>
<td style="text-align: center;"><span class="math inline">\(&gt;60\)</span></td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;"><span class="math inline">\(&gt;21\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\delta_i\)</span></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>There were <span class="math inline">\(\sum \delta_i = 7\)</span> deaths during the study with <span class="math display">\[\sum \delta_i t_i = 155 \quad \textrm{and } \sum (1- \delta_i) c_i = 153.\]</span> Thus our estimate of the expected number of deaths per day (<span class="math inline">\(\hat{\lambda}\)</span>) is 0.0227 and the m.l.e. of the mean lifetime is <span class="math inline">\(\hat{\mu} = 1/\hat{\lambda} = 44.0\)</span> days. We can find a 95% confidence interval for <span class="math inline">\(\hat{\lambda}\)</span> as (0.00586, 0.0395).</p>
</section>
<section id="allowing-random-censoring-only-examinable-in-mps438" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="allowing-random-censoring-only-examinable-in-mps438"><span class="header-section-number">3.1.5</span> Allowing Random Censoring (only examinable in MPS438)</h3>
<p>A full treatment of this topic is beyond the scope of this module but we’ll consider the simplest approaches and state some results. The simplest case is the where observations are collected over a fixed time interval of length <span class="math inline">\(T_{max}\)</span>. To introduce the randomness of the censoring in a simple way suppose subjects arrive uniformly over the interval <span class="math inline">\((0, T_{max})\)</span> and that there is no other loss to follow up, so the censoring is caused only because the study ends before the subject experiences the event.</p>
<p>Let <span class="math inline">\(\delta_i\)</span> be the censoring indicator. It can be shown (you should verify it) that <span class="math display">\[
E[\delta_i] = 1 - \frac{1-e^{-\lambda T_{max}}}{\lambda T_{max}},
\]</span> and so analogously to the previous section <span class="math display">\[
s.e.(\hat{\lambda}) \approx \frac{\hat{\lambda}}{\sqrt{n\left(1 - \frac{1-e^{-\lambda T_{max}}}{\lambda T_{max}}\right)}}.
\]</span> If recruitment is over a shorter period <span class="math inline">\(R\)</span> but the study lasts for a time <span class="math inline">\(T_{max}\)</span> so the arrival times are uniformly spread over <span class="math inline">\((0, R)\)</span> then we have <span class="math display">\[
E[\delta_i] = 1 - \frac{1-e^{-\lambda (T_{max} - R)} - e^{-\lambda T_{max}}}{\lambda R}
\]</span> with obvious modification to the standard error.</p>
</section>
</section>
<section id="survreg" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="survreg"><span class="header-section-number">3.2</span> Fitting Parametric models in R</h2>
<p>The basic function to perform estimation using these models is <code>survreg()</code> and one of the arguments specifies which distribution to use from the options <code>weibull</code>, <code>exponential</code>, <code>gaussian</code>, <code>logistic</code>, <code>lognormal</code> and <code>loglogistic</code>. The default is <code>weibull</code>. It is also possible to use other distributions if the distribution function and density function are specified (see the help system if needed).</p>
<p>Care needs to be taken with the parameterization in <code>survreg()</code> since it models the parameters in what may not initially seem the most intuitive way. It generally presents value for log of the parameter and these will need interpreting/transforming back into the actual survival times themselves. The reason for this is that <code>survreg</code> can be adapted to more complicated models (as we will later) where this parameterisation is more natural.</p>
<ul>
<li><p>For the exponential model with rate parameter <span class="math inline">\(\lambda\)</span> (or mean <span class="math inline">\(\lambda^{-1}\)</span>), the MLE is <span class="math inline">\(\hat \lambda =\exp(-\beta_0)\)</span>, where <span class="math inline">\(\beta_0\)</span> is the <code>survreg()</code> intercept. It follows that <span class="math inline">\(\beta_0\)</span> represents the log(mean survival time). It is easiest to calculate a CI for <span class="math inline">\(-\beta_0\)</span>, and then exponentiate the CI limits (base e) to get a confidence interval for the true value of <span class="math inline">\(\lambda\)</span>.</p></li>
<li><p>For the Weibull model, the MLE of <span class="math inline">\(\lambda\)</span> is <span class="math inline">\(\hat \lambda=\exp(-\beta_0)\)</span> as for the exponential case. <span class="math inline">\(\hat \gamma\)</span> is the reciprocal of the ‘scale’ parameter provided directly in the <code>survreg()</code> summary.</p></li>
</ul>
<section id="fitting-an-exponential-model-to-the-lung-cancer-data" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="fitting-an-exponential-model-to-the-lung-cancer-data"><span class="header-section-number">3.2.1</span> Fitting an Exponential model to the lung cancer data</h3>
<p>We illustrate fitting a distribution to the lung cancer survival times. As with calculation of the non-parametric Kaplan-Meier estimate, we need to use the <code>Surv()</code> function to create a survival object which contains the information on censoring. This object can then be used in fitting any of the available survival regression models.</p>
<p>We fit an exponential model as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>lcancer <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">72</span>, <span class="dv">51</span>, <span class="dv">60</span>, <span class="dv">33</span>, <span class="dv">27</span>, <span class="dv">14</span>, <span class="dv">24</span>, <span class="dv">4</span>, <span class="dv">21</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">censor =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>lcancer_sv <span class="ot">&lt;-</span> <span class="fu">Surv</span>(lcancer<span class="sc">$</span>time, lcancer<span class="sc">$</span>censor, <span class="at">type =</span> <span class="st">"right"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>lcancer_regexp <span class="ot">&lt;-</span> <span class="fu">survreg</span>(lcancer_sv <span class="sc">~</span> <span class="dv">1</span>, <span class="at">dist =</span> <span class="st">"exponential"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lcancer_regexp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survreg(formula = lcancer_sv ~ 1, dist = "exponential")
            Value Std. Error  z      p
(Intercept) 3.784      0.378 10 &lt;2e-16

Scale fixed at 1 

Exponential distribution
Loglik(model)= -33.5   Loglik(intercept only)= -33.5
Number of Newton-Raphson Iterations: 4 
n= 10 </code></pre>
</div>
</div>
<p>Thus <span class="math display">\[\hat{\lambda}=\frac{1}{\text{exp(intercept)}} = \frac{1}{\text{exp}(3.78)} = 0.0228\]</span> and a 95% confidence interval for <span class="math inline">\(\lambda\)</span> is <span class="math display">\[\frac{1}{\exp( 3.78 \pm 1.96 \times 0.378)} = (0.0108, 0.0479)\]</span> The standard errors in the R output are not the same as the standard errors calculated from Equation @ref(eq:censexpvarobs). That would give an approximate standard error of <span class="math inline">\(\hat \lambda\)</span> as <span class="math display">\[\frac{1}{\sqrt{7}\exp(3.78)} = 0.008626 \hspace{1cm} \left[ s.e.(\hat{\lambda}) \approx \frac{\hat{\lambda}}{\sqrt{\sum \delta_i}} \right]\]</span> and a confidence interval of (0.00589, 0.0397). These illustrate that calculations of standard errors and confidence intervals depend on the approach being used although the differences may often not be very large.</p>
</section>
<section id="fitting-a-weibull-model-to-the-tumour-remission-data" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="fitting-a-weibull-model-to-the-tumour-remission-data"><span class="header-section-number">3.2.2</span> Fitting a Weibull model to the tumour remission data</h3>
<p>The default distribution for <code>survreg</code> is the Weibull distribution so you don’t need to specify a distribution argument to fit a Weibull distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>tumour <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="fl">6.5</span>, <span class="fl">6.5</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">15</span>, <span class="fl">8.4</span>, <span class="dv">4</span>, <span class="fl">5.7</span>, <span class="fl">10.1</span>),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">censor =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>tumour_sv <span class="ot">&lt;-</span> <span class="fu">Surv</span>(tumour<span class="sc">$</span>time, tumour<span class="sc">$</span>censor, <span class="at">type =</span> <span class="st">"right"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>tumourSurvWeib <span class="ot">&lt;-</span> <span class="fu">survreg</span>(tumour_sv <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> tumour)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tumourSurvWeib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survreg(formula = tumour_sv ~ 1, data = tumour)
             Value Std. Error     z      p
(Intercept)  2.420      0.147 16.41 &lt;2e-16
Log(scale)  -1.018      0.312 -3.26 0.0011

Scale= 0.361 

Weibull distribution
Loglik(model)= -18.3   Loglik(intercept only)= -18.3
Number of Newton-Raphson Iterations: 6 
n= 10 </code></pre>
</div>
</div>
<p>As mentioned in <a href="background.html#sec-weibull" class="quarto-xref"><span>Section 1.5.2</span></a>, there are different parameterisations of the Weibull distribution, in particular, <code>survreg()</code> uses a different parameterisation to <code>dweibull</code>, <code>pweibull</code> etc in R. We relate each to the <code>summary</code> output above as follows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><a href="background.html#sec-weibull" class="quarto-xref"><span>Section 1.5.2</span></a> parameterisation</th>
<th>R <code>dweibull</code> parameterisation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat{\lambda} = \exp(-\)</span><code>(Intercept)</code>)</td>
<td><span class="math inline">\(\hat{\sigma} = \exp(\)</span><code>(Intercept)</code>)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat{\gamma} = \exp(-\)</span><code>Log(scale)</code>)</td>
<td><span class="math inline">\(\hat{a} = \exp(-\)</span><code>Log(scale)</code>)</td>
</tr>
</tbody>
</table>
<p>From the <code>R</code> output we see that <span class="math inline">\(\hat \lambda = \exp(-2.42)=0.089\)</span> and <span class="math inline">\(\hat \gamma = 1/0.361 = 2.8\)</span> . Remember that forcing the <span class="math inline">\(\gamma\)</span> parameter of the Weibull distribution to be 1 reduces the Weibull model to an exponential model.</p>
</section>
<section id="checking-goodness-of-fit" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="checking-goodness-of-fit"><span class="header-section-number">3.2.3</span> Checking goodness of fit</h3>
<p>A visual way to check goodness of fit is to plot the fitted survivor function on top of a Kaplan-Meier plot. Here is an example in R for the lung cancer data. Recall that we obtained <span class="math inline">\(\hat{\lambda}=0.0228\)</span> for the exponential model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>lcancer <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">72</span>, <span class="dv">51</span>, <span class="dv">60</span>, <span class="dv">33</span>, <span class="dv">27</span>, <span class="dv">14</span>, <span class="dv">24</span>, <span class="dv">4</span>, <span class="dv">21</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">censor =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>lcancer_sv <span class="ot">&lt;-</span> <span class="fu">Surv</span>(lcancer<span class="sc">$</span>time, lcancer<span class="sc">$</span>censor, <span class="at">type =</span> <span class="st">"right"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>lcancerSurv <span class="ot">&lt;-</span> <span class="fu">survfit</span>(lcancer_sv <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># use ggsurvplot to obtain the Kaplan-Meier estimate...</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># ...but assign the result to a variable (KMplot) instead of displaying</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>KMplot <span class="ot">&lt;-</span> <span class="fu">ggsurvplot</span>(lcancerSurv, <span class="at">data =</span> lcancer_sv,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.int.style =</span> <span class="st">"ribbon"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">conf.int.alpha =</span> <span class="fl">0.4</span>, <span class="at">xlab =</span> <span class="st">"Time (months)"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">legend =</span> <span class="st">"none"</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="do">## KMplot$plot is a ggplot2 object that we can add to</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="do">## We use stat_function to add the exponential fit</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="do">## The survivor function is 1 - pexp(x, rate = 0.023)</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="do">## as the m.l.e of lambda was 0.023</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="do">## This will draw the Kaplan-Meier estimate and add the exponential fit:</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>KMplot<span class="sc">$</span>plot <span class="sc">+</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">-</span><span class="fu">pexp</span>(x, <span class="at">rate =</span> <span class="fl">0.023</span>), <span class="at">color =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="parametric_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will do the same for the Weibull example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tumour <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="fl">6.5</span>, <span class="fl">6.5</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">15</span>, <span class="fl">8.4</span>, <span class="dv">4</span>, <span class="fl">5.7</span>, <span class="fl">10.1</span>),</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">censor =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>tumour_sv <span class="ot">&lt;-</span> <span class="fu">Surv</span>(tumour<span class="sc">$</span>time, tumour<span class="sc">$</span>censor, <span class="at">type =</span> <span class="st">"right"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>tumourSurv <span class="ot">&lt;-</span> <span class="fu">survfit</span>(tumour_sv <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>KMplot <span class="ot">&lt;-</span> <span class="fu">ggsurvplot</span>(tumourSurv, <span class="at">data =</span> tumour,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.int.style =</span> <span class="st">"ribbon"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">conf.int.alpha =</span> <span class="fl">0.4</span>, <span class="at">xlab =</span> <span class="st">"Time (months)"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">legend =</span> <span class="st">"none"</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>KMplot<span class="sc">$</span>plot <span class="sc">+</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pweibull</span>(x, <span class="at">scale =</span> <span class="fu">exp</span>(<span class="fl">2.42</span>), </span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">shape =</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.018</span>)), <span class="at">color =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="parametric_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="tasks" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="tasks"><span class="header-section-number">3.3</span> Tasks</h2>
<p>The data below give the time to relapse (in weeks), following remission, for a group of leukaemia patients treated with a particular drug “Drug-6-MP”: (* indicates a right censored value).</p>
<p><span class="math display">\[6^*, 6, 6, 6, 7, 9^*, 10^*, 10, 11^*, 13, 16,\]</span> <span class="math display">\[17^*, 19^*, 20^*, 22, 23, 25^*, 32^*, 34^*, 35^*\]</span> These are the data used in the Chapter 2 Tasks. Here, we will suppose the remission times follow an exponential distribution with rate parameter <span class="math inline">\(\lambda\)</span>.</p>
<ol type="1">
<li>Estimate the MLE of the rate parameter <span class="math inline">\(\lambda\)</span>.</li>
<li>Calculate the median relapse time.</li>
<li>Calculate the inter-quartile range of the relapse time.</li>
<li>Calculate the probability that a leukaemia patient will not relapse within 6 weeks of remission.</li>
<li>Estimate the density function of relapse time at 6 weeks.</li>
<li>Estimate the hazard function of relapse time at 6 weeks.</li>
<li>Calculate a 95% confidence interval for <span class="math inline">\(\lambda\)</span>.</li>
<li>A similar study estimates that 48% of leukaemia patients in the Drug-6-MP group do not relapse for at least 15 weeks. Is the confidence interval in (7) consistent with this finding?</li>
<li>In a similar Drug-6-MP group of 10 leukaemia patients, estimate the probability that at least 2 patients relapse within 8 weeks.</li>
<li>Calculate a 95% confidence interval for expected relapse time.</li>
<li>Calculate a 95% confidence interval for median relapse time.</li>
<li>In R, fit an exponential failure time distribution to the relapse time data for the Drug-6-MP patients. Assess the evidence that a Weibull distribution is more appropriate than the exponential distribution as a model of the relapse time.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./survivor.html" class="pagination-link" aria-label="Estimating survivor functions: life-tables and Kaplan-Meier">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimating survivor functions: life-tables and Kaplan-Meier</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./twosample.html" class="pagination-link" aria-label="Two Sample Comparisons">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Two Sample Comparisons</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>