<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Proportional Hazards Models – Survival analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./aft.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./proportionalhazards.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Survival analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background and Basic Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survivor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estimating survivor functions: life-tables and Kaplan-Meier</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parametric.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parametric one-sample models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./twosample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Two Sample Comparisons</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Accelerated Failure Time (AFT) Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proportionalhazards.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#which-aft-models-exhibit-the-proportional-hazards-property" id="toc-which-aft-models-exhibit-the-proportional-hazards-property" class="nav-link active" data-scroll-target="#which-aft-models-exhibit-the-proportional-hazards-property"><span class="header-section-number">6.1</span> Which AFT models exhibit the proportional hazards property?</a></li>
  <li><a href="#parameter-estimation" id="toc-parameter-estimation" class="nav-link" data-scroll-target="#parameter-estimation"><span class="header-section-number">6.2</span> Parameter Estimation</a>
  <ul class="collapse">
  <li><a href="#the-partial-likelihood-approach" id="toc-the-partial-likelihood-approach" class="nav-link" data-scroll-target="#the-partial-likelihood-approach"><span class="header-section-number">6.2.1</span> The Partial Likelihood approach</a></li>
  </ul></li>
  <li><a href="#RCoxPh" id="toc-RCoxPh" class="nav-link" data-scroll-target="#RCoxPh"><span class="header-section-number">6.3</span> Fitting a proportional hazards model in R</a></li>
  <li><a href="#what-the-r-output-tells-us" id="toc-what-the-r-output-tells-us" class="nav-link" data-scroll-target="#what-the-r-output-tells-us"><span class="header-section-number">6.4</span> What the R output tells us</a></li>
  <li><a href="#including-interaction-terms" id="toc-including-interaction-terms" class="nav-link" data-scroll-target="#including-interaction-terms"><span class="header-section-number">6.5</span> Including interaction terms</a></li>
  <li><a href="#model-checking" id="toc-model-checking" class="nav-link" data-scroll-target="#model-checking"><span class="header-section-number">6.6</span> Model Checking</a>
  <ul class="collapse">
  <li><a href="#log-log-plots-for-factor-variables" id="toc-log-log-plots-for-factor-variables" class="nav-link" data-scroll-target="#log-log-plots-for-factor-variables"><span class="header-section-number">6.6.1</span> Log-Log Plots for Factor Variables</a></li>
  <li><a href="#log-log-implementation-in-r" id="toc-log-log-implementation-in-r" class="nav-link" data-scroll-target="#log-log-implementation-in-r"><span class="header-section-number">6.6.2</span> Log-Log Implementation in <span class="math inline">\(R\)</span></a></li>
  <li><a href="#residual-plots" id="toc-residual-plots" class="nav-link" data-scroll-target="#residual-plots"><span class="header-section-number">6.6.3</span> Residual Plots</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Aims for this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter, we will study another class of regression models, proportional hazards models (also known as “Cox regression models), for relating the survival time of an individual to explanatory variables for that individual. In particular we will</p>
<ol type="1">
<li><p>study the defining characteristics of a proportional hazards model: how explanatory variables modify the hazard function;</p></li>
<li><p>understand how the parameters of a proportional hazards model estimated using likelihood methods;</p></li>
<li><p>fit proportional hazards models in R, and interpret the R output;</p></li>
<li><p>study some methods for checking model assumptions.</p></li>
</ol>
</div>
</div>
<p>An alternative approach to modelling the dependence of the failure time distribution on explanatory variables <span class="math inline">\(\mathbf{x}\)</span> is through the hazard function with <span class="math display">\[
h(t; \mathbf{x}) = \psi(\mathbf{x}; \boldsymbol{\beta}) h_0(t),
\]</span> where <span class="math inline">\(h_0(t)\)</span> corresponds to the hazard for an individual under the baseline conditions where <span class="math inline">\(\mathbf{x} = \mathbf{0}\)</span> and we require <span class="math inline">\(\psi(\mathbf{x}=\mathbf{0}; \boldsymbol{\beta}) = 1\)</span>. Typically we choose <span class="math display">\[
\psi(\mathbf{x}; \boldsymbol{\beta}) = e^{\boldsymbol{\beta}' \mathbf{x}}
\]</span> so that <span class="math display">\[
h(t; \mathbf{x}) = e^{\boldsymbol{\beta}' \mathbf{x}} h_0(t).
\]</span> This is a semi-parametric model proposed by Sir David Cox <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. This work has become so widely used that his original paper is one of the most cited mathematical papers in history.</p>
<p>Proportional-hazards is called semi-parametric since the baseline hazard <span class="math inline">\(h_0(t)\)</span> does not need to be specified. The dependence of the failure time <span class="math inline">\(T\)</span> on explanatory variables <span class="math inline">\(\mathbf{x}\)</span> is precisely modelled; but actual distribution of failure is not parametrically specified. It is particularly useful in medical situations where</p>
<ul>
<li><p>it is important to know which prognostic variables have an effect and to what extent</p></li>
<li><p><strong>but</strong> knowing the actual distribution of survival time is not as important.</p></li>
</ul>
<p>One should also note that for two patients with covariates <span class="math inline">\(\mathbf{x_1}\)</span> and <span class="math inline">\(\mathbf{x_2}\)</span> we have <span class="math display">\[\begin{align}
\frac{h(t; \mathbf{x_1})}{h(t; \mathbf{x_2})} &amp;= \frac{e^{\boldsymbol{\beta}' \mathbf{x_1}}}{e^{\boldsymbol{\beta}' \mathbf{x_2}}} \\
&amp;= e^{\boldsymbol{\beta}'(\mathbf{x_1}-\mathbf{x_2})}
\end{align}\]</span> which is <strong>independent of time</strong>. Hence hazard functions for any two patients are proportional over time as the linear component of the model does not vary with time.</p>
<section id="which-aft-models-exhibit-the-proportional-hazards-property" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="which-aft-models-exhibit-the-proportional-hazards-property"><span class="header-section-number">6.1</span> Which AFT models exhibit the proportional hazards property?</h2>
<p>Suppose <span class="math inline">\(T \sim Exp(\lambda)\)</span> then for an AFT with an exponential survival time the hazard function is <span class="math display">\[h(t;\mathbf{x}) = \lambda e^{-\boldsymbol{\beta}' \mathbf{x}}.\]</span> It follows that the ratio of any two hazards for two patients with covariates <span class="math inline">\(\mathbf{x_1}\)</span> and <span class="math inline">\(\mathbf{x_2}\)</span> is of the form above: <span class="math display">\[
\frac{h(t; \mathbf{x_1})}{h(t; \mathbf{x_2})} = \frac{\lambda e^{-\boldsymbol{\beta}' \mathbf{x_1}}}{\lambda e^{-\boldsymbol{\beta}' \mathbf{x_2}}}
= e^{-\boldsymbol{\beta}'(\mathbf{x_1}-\mathbf{x_2})}
\]</span></p>
<p>and therefore has the proportional hazards property. (The change of sign from <span class="math inline">\(\boldsymbol{\beta}\)</span> to <span class="math inline">\(-\boldsymbol{\beta}\)</span> doesn’t matter: the important point is that the ratio is constant over time).</p>
<p>Similarly if <span class="math inline">\(T \sim Weibull(\lambda, \gamma)\)</span> then for an AFT with a Weibull survival time, the hazard is <span class="math display">\[h(t;\mathbf{x}) =\lambda^\gamma \gamma t^{\gamma-1}exp(-\gamma\mathbf{\beta}' \mathbf{x}).\]</span> Hence the ratio of any two hazards for two patients with covariates <span class="math inline">\(\mathbf{x_1}\)</span> and <span class="math inline">\(\mathbf{x_2}\)</span> is <span class="math display">\[
\frac{h(t; \mathbf{x_1})}{h(t; \mathbf{x_2})} = \frac{\lambda^\gamma \gamma t^{\gamma-1}\exp(-\gamma\mathbf{\beta}' \mathbf{x_1})}{\lambda^\gamma \gamma t^{\gamma-1}\exp(-\gamma\mathbf{\beta}' \mathbf{x_2})}
= e^{-\gamma\boldsymbol{\beta}'(\mathbf{x_1}-\mathbf{x_2})},
\]</span></p>
<p>which is again independent of time and therefore has the proportional hazards property. Note that because the exponential is a special case of the Weibull we only really needed to demonstrate this property for the Weibull distribution. The Weibull distribution (and hence Exponential as a special case) is the only distribution for which the corresponding AFT model has the proportional hazards property.</p>
</section>
<section id="parameter-estimation" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="parameter-estimation"><span class="header-section-number">6.2</span> Parameter Estimation</h2>
<p>Consider our typical situation where we have <span class="math inline">\(n\)</span> individuals and for each we have observed <span class="math display">\[\begin{align}
t_i &amp;= \min(\textrm{Failure time}, \textrm{Time of right censoring}) \\
\delta_i &amp;= \left\{ \begin{array}{rl}
                1 &amp; \textrm{if $i$ is observed to fail} \\
                0 &amp; \textrm{if $i$ is censored}
               \end{array} \right. \\
\mathbf{x_i} &amp;= \textrm{$p$ dimensional vector of explanatory variables}
\end{align}\]</span> If we wish to model this with a proportional hazards model then <span class="math display">\[\begin{align}
h(t; x) &amp;=   e^{\boldsymbol{\beta}' \mathbf{x}} h_0(t) \\
S(t; x) &amp;=   \exp \left\{ -\int_0^t h(t)dt \right\} \\
&amp;= \exp \left\{ -\int_0^t e^{\boldsymbol{\beta}' \mathbf{x}} h_0(t)dt \right\} \\
&amp;= \exp \left\{ -e^{\boldsymbol{\beta}' \mathbf{x}} \int_0^t  h_0(t)dt \right\} \\
&amp;= \left[ S_0(t) \right]^{e^{\boldsymbol{\beta}' \mathbf{x}}} \\
f(t; \mathbf{x}) &amp;= h(t;\mathbf{x}) S(t;\mathbf{x}) = e^{\boldsymbol{\beta}' \mathbf{x}} h_0(t) S(t) .
\end{align}\]</span> We can do our usual approach to writing down the likelihood of the censored and observed data <span class="math display">\[\begin{align}
\textrm{Likelihood} &amp;= \prod_{i=1}^n f(t_i;\mathbf{x_i})^{\delta_i} S(c_i;\mathbf{x_i})^{1-\delta_i} \\
&amp;= \prod_{i=1}^n \left[\frac{h(t_i;\mathbf{x_i})}{S(t_i;\mathbf{x_i})}\right]^{\delta_i} S(c_i;\mathbf{x_i})^{1-\delta_i}.
\end{align}\]</span> However, this involves the unspecified baseline hazard <span class="math inline">\(h_0(t)\)</span> and so to proceed further we would need to specify its parametric form. However we don’t want to do that and so we will proceed by working with the partial likelihood.</p>
<section id="the-partial-likelihood-approach" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="the-partial-likelihood-approach"><span class="header-section-number">6.2.1</span> The Partial Likelihood approach</h3>
<p>In the proportional hazards model, the baseline hazard <span class="math inline">\(h_0(t)\)</span> is unspecified: the model does not attempt to describe when failure events are likely to occur. Instead, the model describes how some individuals have a higher risk of failure relative to others, through a relative increase in their hazard. Hence the information in the data that is relevant to the model is not the actual failure times, but <em>who</em> had the failure event whenever a failure event occurred. In particular, what was it about that particular individual (what were their covariates) that might have caused them to have the failure event, rather than someone else.</p>
<p>We work with the order that people fail i.e.&nbsp;who out of the people at risk of failing actually does so at each time. We define the random variable</p>
<ul>
<li><span class="math inline">\(\phi_j\)</span>: the index of the individual who fails at the <span class="math inline">\(j^{th}\)</span> failure time, conditional on that failure time being <span class="math inline">\(t_{(j)}\)</span>. For <span class="math inline">\(n\)</span> individuals, no censoring, and <span class="math inline">\(n\)</span> distinct failure times, we would have <span class="math inline">\(\phi_j\in \{1,\ldots,n\}\)</span></li>
</ul>
<p>We first order the failure times <span class="math display">\[t_{(1)}&lt;t_{(2)}&lt; \ldots &lt; t_{(n)}.\]</span> This creates a corresponding ordering on the rest of the variables so that</p>
<ul>
<li>the <span class="math inline">\(j^{th}\)</span> individual who fails (at time <span class="math inline">\(t_{(j)}\)</span>) is labelled <span class="math inline">\(i_{(j)}\)</span>.</li>
<li>This individual has censoring indicator value <span class="math inline">\(\delta_{(j)}\)</span> and explanatory covariates <span class="math inline">\(\mathbf{x_{(j)}}\)</span>.</li>
</ul>
<p><strong>Partial Likelihood without Censoring</strong></p>
<p>Suppose that we have no censoring in the data and that there are no ties in failure times i.e.&nbsp;only one individual dies at each death time. Let us order the observed failure times and denote them by <span class="math inline">\(t_{(1)}&lt;t_{(2)}&lt; \ldots &lt; t_{(n)}\)</span>. Also let us create an order amongst the individuals so that the individual who dies at failure time <span class="math inline">\(t_{(j)}\)</span> is <span class="math inline">\(i_{(j)}\)</span> i.e.&nbsp;<span class="math inline">\(i_{(j)} = k\)</span> if and only if <span class="math inline">\(t_k = t_{(j)}\)</span>. Finally let define a risk set <span class="math display">\[\mathcal{R}(t) = \{ \textrm{The set of individuals alive and in the trial just before time }t \}.\]</span> Let <span class="math inline">\(t^\dagger = \{ t_{(1)}, \ldots, t_{(n)}\}\)</span>. We want to work with the likelihood or probability of the observed order <span class="math inline">\((i_{(1)}, \ldots, i_{(n)})\)</span> in which the individuals fail conditional on those failure times i.e.&nbsp;<span class="math display">\[P(\phi_1 = i_{(1)}, \phi_2 = i_{(2)}, \ldots,  \phi_n = i_{(n)}|t^\dagger)\]</span> Using repeated conditioning we can split this probability as <span class="math display">\[\begin{align}
  &amp;P(\phi_1 = i_{(1)}, \phi_2 = i_{(2)}, \ldots,  \phi_n = i_{(n)} | t^\dagger) \\
  =&amp;P(\phi_1 = i_{(1)}| t^\dagger) \prod_{j=2}^{n}P(\phi_j = i_{(j)} | \phi_1 = i_{(1)}, \ldots,  \phi_{j-1} = i_{(j-1)},t^\dagger)
\end{align}\]</span> and we can deal with each of these probabilities separately. Now <span class="math display">\[P(\phi_j = i | \phi_1 = i_{(1)}, \phi_2 = i_{(2)}, \ldots,  \phi_{j-1} = i_{(j-1)}, t^\dagger))\]</span> is the probability that individual <span class="math inline">\(i\)</span> fails at time <span class="math inline">\(t_{(j)}\)</span> given that we know one individual does fail at that time from those individuals at risk (i.e.&nbsp;in the risk set <span class="math inline">\(\mathcal{R}(t_{(j)}))\)</span>. This can be thought of as picking an individual at random from the risk set where the probability you pick any individual <span class="math inline">\(k\)</span> is proportional to that individuals hazard <span class="math inline">\(h(t_{(j)}; \mathbf{x_k})\)</span>. As such it can be written as <span class="math display">\[\begin{align}
\frac{h(t_{(j)}; \mathbf{x_i})}{\sum_{k \in \mathcal{R}(t_{(j)})} h(t_{(j)}; \mathbf{x_k})} &amp;= \frac{e^{\boldsymbol{\beta}' \mathbf{x_i}} h_0(t_{(j)})}{\sum_{k \in \mathcal{R}(t_{(j)})} e^{\boldsymbol{\beta}' \mathbf{x_k}} h_0(t_{(j)})} \\
&amp;= \frac{e^{\boldsymbol{\beta}' \mathbf{x_i}}}{\sum_{k \in \mathcal{R}(t_{(j)})} e^{\boldsymbol{\beta}' \mathbf{x_k}}}
\end{align}\]</span> after cancelling the baseline hazards. Putting all these terms together, we can write down the probability of the observed order <span class="math inline">\((i_{(1)}, \ldots, i_{(n)})\)</span> as <span class="math display">\[P(\phi_1 = i_{(1)}, \phi_2 = i_{(2)}, \ldots,  \phi_n = i_{(n)}|t_{(1)}, \ldots, t_{(n)}) = \prod_{j=1}^n \frac{e^{\boldsymbol{\beta}' \mathbf{x_{(j)}}}}{\sum_{k \in \mathcal{R}(t_{(j)})} e^{\boldsymbol{\beta}' \mathbf{x_k}}}\]</span> where <span class="math inline">\(\mathbf{x_{(j)}}\)</span> is the vector of explanatory variables for individual <span class="math inline">\(i_{(j)}\)</span> i.e.&nbsp;the <span class="math inline">\(j^{th}\)</span> individual to fail.</p>
<p><strong>Partial Likelihood with Censoring</strong></p>
<p>We can extend the above idea to also include censored observation by adjusting the risk set <span class="math inline">\(\mathcal{R}(t)\)</span> accordingly to take account of those individuals who have been censored by time <span class="math inline">\(t\)</span>. We also only need to take account of the actual failure times i.e.&nbsp;when <span class="math inline">\(\delta_i = 1\)</span> for each term in the product. As such we can write down a partial likelihood for the observed data and parameter <span class="math inline">\(\boldsymbol{\beta}\)</span> as <span class="math display">\[L(\boldsymbol{\beta}) = \prod_{j=1}^n \left( \frac{e^{\boldsymbol{\beta}' \mathbf{x_{(j)}}}}{\sum_{k \in \mathcal{R}(t_{(j)})} e^{\boldsymbol{\beta}' \mathbf{x_k}}} \right)^{\delta_{(j)}}\]</span> Note that individuals for whom the survival time is censored do not contribute to the numerator but they do enter the summation over the risk set at death times of subject less than the censored time.</p>
<p><strong>Notes on the Partial Likelihood Approach</strong></p>
<ul>
<li><p>If there are no censored observations this is a conditional likelihood, conditional on the observed failure times <span class="math inline">\(t_{(1)},t_{(2)},\ldots,t_{(n)}\)</span>.</p></li>
<li><p>With censored observations this is instead known as a partial likelihood. The use of such a partial likelihood was justified by Cox (1975)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. He showed that the usual likelihood methods apply in this case. So we maximize the (partial) likelihood to estimate <span class="math inline">\(\boldsymbol{\beta}\)</span> by <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> and asymptotically <span class="math display">\[\hat{\boldsymbol{\beta}} \sim N \left( \boldsymbol{\beta}, \left[ -\frac{\partial^2 l}{\partial \beta_i \partial \beta_j} \right]^{-1}_{\hat{\boldsymbol{\beta}}} \right)\]</span> where <span class="math inline">\(l\)</span> is the log likelihood.</p></li>
<li><p><strong>Ties (Peto’s adjustment)</strong> If we have data with ties in the failure times i.e.&nbsp;<span class="math display">\[\begin{align}
t_{(1)}&lt;t_{(2)}&lt;\ldots&lt;t_{(k)} &amp; \quad \textrm{the $k$ distinct survival times} \\
d_{(1)}, d_{(2)},\ldots, d_{(k)} &amp; \quad \textrm{numbers of deaths at these times} \\
\mathcal{D}(t_{(1)}), \mathcal{D}(t_{(2)}),\ldots, \mathcal{D}(t_{(k)}) &amp; \quad \textrm{death set at $t_{(j)}$}
\end{align}\]</span> we can allow each of <span class="math inline">\(d_{(j)}\)</span> deaths at <span class="math inline">\(t_{(j)}\)</span> to contribute a factor (as before) to partial likelihood, each with the same risk set <span class="math inline">\(\mathcal{R}(t_{(j)})\)</span> so that <span class="math display">\[L(\boldsymbol{\beta}) = \prod_{j=1}^n \left( \frac{e^{ \sum_{k \in \mathcal{D}(t_{(j)})} \boldsymbol{\beta}' \mathbf{x_{k}}}}{\sum_{k \in \mathcal{R}(t_{(j)})} e^{\boldsymbol{\beta}' \mathbf{x_k}}} \right)^{\delta_{(j)}}\]</span> This is satisfactory provided <span class="math inline">\(d_{(j)}/n_{(j)}\)</span> is small, where <span class="math inline">\(n_{(j)}\)</span> is the number of individuals at risk at <span class="math inline">\(t_{(j)}\)</span>.</p></li>
</ul>
</section>
</section>
<section id="RCoxPh" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="RCoxPh"><span class="header-section-number">6.3</span> Fitting a proportional hazards model in R</h2>
<p>Data is available for patients being treated for atrial fibrillation (irregular heart rhythm). The variables in the dataset (available on Blackboard) are as follows</p>
<ul>
<li>drug: a binary covariate representing a new drug treatment of interest with levels A (a placebo representing the baseline) and B (the new drug being tested)</li>
<li>age: a continuous covariate representing the age in years at the start of treatment (45 years have been subtracted from the ages)</li>
<li>hvol: a continuous covariate representing the heart volume in cm<span class="math inline">\(^3\)</span> (700 has been subtracted from all the measurements)</li>
<li>diet: a three-level categorical covariate representing the type of diet with levels “vegan” (baseline), “veggie” and “meat”</li>
<li>digit: a binary covariate representing whether the patient is also being treated with digitalis (a drug derived from the common foxglove plant) with levels “yes” and “no” (baseline)</li>
<li>sex: a binary covariate representing the sex of the patient with levels “male” and “female” (baseline)</li>
</ul>
<p>The purpose of the proposed new drug treatment is to maintain normal heart rhythm and the interest is in the time to relapse. We fit a proportional hazards models in R using the <code>coxph</code> function as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"datasets/arfib.RData"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>arfib_sv <span class="ot">&lt;-</span> <span class="fu">Surv</span>(afib<span class="sc">$</span>time, afib<span class="sc">$</span>cens, <span class="at">type =</span> <span class="st">"right"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>afibph <span class="ot">&lt;-</span> <span class="fu">coxph</span>(arfib_sv <span class="sc">~</span> drug <span class="sc">+</span> age <span class="sc">+</span> hvol <span class="sc">+</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                           diet <span class="sc">+</span> digit <span class="sc">+</span> sex,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> afib)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(afibph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = arfib_sv ~ drug + age + hvol + diet + digit + 
    sex, data = afib)

  n= 40, number of events= 34 

               coef exp(coef) se(coef)      z Pr(&gt;|z|)    
drugB      -2.09912   0.12256  0.60237 -3.485 0.000493 ***
age        -0.02650   0.97385  0.01994 -1.329 0.183764    
hvol        0.08176   1.08520  0.01446  5.652 1.58e-08 ***
dietmeat    1.27795   3.58928  0.58380  2.189 0.028594 *  
dietveggie -0.40800   0.66498  0.58999 -0.692 0.489232    
digityes   -0.70111   0.49603  0.46255 -1.516 0.129583    
sexmale     0.81621   2.26192  0.51241  1.593 0.111181    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

           exp(coef) exp(-coef) lower .95 upper .95
drugB         0.1226     8.1590   0.03764    0.3991
age           0.9738     1.0269   0.93653    1.0127
hvol          1.0852     0.9215   1.05486    1.1164
dietmeat      3.5893     0.2786   1.14308   11.2703
dietveggie    0.6650     1.5038   0.20922    2.1135
digityes      0.4960     2.0160   0.20035    1.2281
sexmale       2.2619     0.4421   0.82855    6.1750

Concordance= 0.94  (se = 0.017 )
Likelihood ratio test= 71.99  on 7 df,   p=6e-13
Wald test            = 33.8  on 7 df,   p=2e-05
Score (logrank) test = 55.75  on 7 df,   p=1e-09</code></pre>
</div>
</div>
<p>To describe this model mathematically we will need seven covariates as follows:</p>
<ul>
<li><span class="math inline">\(x_1\)</span> is a binary indicator representing drug treatment (<span class="math inline">\(x_1\)</span> is 1 for drug “B” and is 0 for drug “A”)</li>
<li><span class="math inline">\(x_2\)</span> represents age</li>
<li><span class="math inline">\(x_3\)</span> represents heart volume</li>
<li><span class="math inline">\(x_4\)</span> is a binary indicator representing “veggie” (<span class="math inline">\(x_4\)</span> is 1 if they are vegetarian, 0 if they are not)</li>
<li><span class="math inline">\(x_5\)</span> is a binary indicator representing “meat” (<span class="math inline">\(x_5\)</span> is 1 if they eat meat, 0 if they do not)</li>
<li><span class="math inline">\(x_6\)</span> is a binary indicator representing whether the patient is also being treated with digitalis (<span class="math inline">\(x_6\)</span> is 1 if they are, 0 if they are not)</li>
<li><span class="math inline">\(x_7\)</span> is a binary indicator representing their sex (<span class="math inline">\(x_7\)</span> is 1 if they are male, 0 if female)</li>
</ul>
<p>The model we are fitting for an individual with covariates <span class="math inline">\(\mathbf{x} = (x_1, \ldots, x_7)'\)</span> is <span class="math display">\[h(t;x) = h_0(t) e^{\beta_1 x_1 + \beta_2 x_2+ \ldots + \beta_7 x_7}\]</span></p>
<p>The model specification in the R code fits only main effects (no interactions). Note that the baseline level of any categorical covariates are <strong>not</strong> included in the output. The baseline level of categorical covariates is always coded as <span class="math inline">\(x_i=0\)</span>. Since the baseline hazard <span class="math inline">\(h_0(t)\)</span> represents the hazard for a patient with all covariates values set to zero it follows that the effect of these baseline levels are all captured by the baseline hazard. The output first shows the significance of the covariates (via p-values) and then the confidence intervals for both <span class="math inline">\(\beta_i\)</span> (the model parameters) and <span class="math inline">\(exp(\beta_i)\)</span>. Recall that Equation @ref(eq:phint) tells us we can interpret the <span class="math inline">\(exp(\beta_i)\)</span> terms as specific hazard ratios which are the primary quantities of interest in a proportional hazards analysis.</p>
<p>There are two main questions of interest:</p>
<ol type="1">
<li><p>How can we quantify the effects of treatment and other covariates on time to relapse?</p></li>
<li><p>How could the analysis consider treatment-covariate interactions?</p></li>
</ol>
</section>
<section id="what-the-r-output-tells-us" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="what-the-r-output-tells-us"><span class="header-section-number">6.4</span> What the R output tells us</h2>
<p>Consider the drug treatment. <span class="math inline">\(x_1=0\)</span> for treatment A (baseline treatment), and <span class="math inline">\(x_1=1\)</span> for treatment B so that <span class="math display">\[\begin{align}
h(t;x_1=0, x_2, x_3 \ldots x_7) &amp;= h_0(t) e^{\beta_2 x_2+ \ldots + \beta_7 x_7} &amp; \quad \textrm{for treatment A} \\
h(t;x_1=1, x_2, x_3 \ldots x_7) &amp;= h_0(t) e^{\beta_1 + \beta_2 x_2+ \ldots + \beta_7 x_7} &amp; \quad \textrm{for treatment B}
\end{align}\]</span> Dividing the treatment B hazard by the treatment A hazard gives <span class="math inline">\(e^{\beta_1}\)</span>. Thus <span class="math inline">\(e^{\beta_1}\)</span> is interpreted as the <strong>hazard ratio</strong> of treatment B to treatment A adjusting for all the other covariates in the model.</p>
<p><strong>Continuous &amp; binary covariates</strong> we can assess whether they significantly affect the hazard by checking the p-values in the usual way. If the parameter is <span class="math inline">\(\beta_i\)</span> then the null and alternative hypotheses for the test are <span class="math display">\[\begin{align}
H_0: \quad &amp; \beta_i=0 \nonumber \\
H_1: \quad &amp; \beta_i \neq 0
\end{align}\]</span></p>
<p><strong>Categorical covariates with</strong> <span class="math inline">\(k\)</span>-levels (<span class="math inline">\(k \geq 3\)</span>) To assess significance we calculate <span class="math inline">\(\chi^2_i = (\hat{\beta_i}/ se(\hat{\beta_i}))^2\)</span> for each of the <span class="math inline">\(k-1\)</span> dummy variables (ignoring the baseline). We then compare <span class="math inline">\(\sum_{i=1}^{k-1} \chi^2_i\)</span> with the quantiles of the <span class="math inline">\(\chi^2_{k-1}\)</span> distribution. When assessing the significance of a <span class="math inline">\(k-\)</span>level factor. It is <strong>wrong</strong> to consider the significance of each level of the factor in isolation (a common exam mistake). You need to make an <strong>aggregated</strong> assessment of the overall effect of the covariate. If the <span class="math inline">\(k-1\)</span> parameters being tested are <span class="math inline">\(\beta_1, \beta_2, \ldots \beta_{k-1}\)</span> then the null and alternative hypotheses for the test are <span class="math display">\[\begin{align}
H_0: \quad &amp; \beta_1=\beta_2= \ldots =\beta_{k-1}=0 \\
H_1: \quad &amp; \beta_1, \beta_2, \ldots \beta_{k-1} \: \text{are not all zero}
\end{align}\]</span></p>
<p>In the atrial fibrilation data, the p-values for age, digitalisation and sex are all less than 0.05 so in each case there isn’t significant evidence at the 5% level to reject the null hypothesis that the parameter is 0 (versus an alternative that it is not 0). For the remaining covariates:</p>
<ul>
<li><p><strong>Treatment:</strong> the p-value is 0.0005 so we have highly significant evidence that treatment has an effect on failure time. <span class="math inline">\(h(t; x_1=1)/h(t; x_1=0) = \exp(\beta_1) &lt; 1\)</span> (since <span class="math inline">\(\beta_1 &lt; 0\)</span>) so treatment B <strong>decreases</strong> the hazard relative to treatment A. A 95% confidence interval for the hazard ratio is (0.04, 0.40) so that the hazard on treatment B is estimated to be between 4% and 40% of hazard on treatment A.</p></li>
<li><p><strong>Heart volume:</strong> the p-value is very small (&lt; 0.00001) so we have extremely significant evidence that treatment has an effect on failure time. <span class="math inline">\(h(t; x_3=v+1)/h(t; x_3=v) = \exp(\beta_3) &gt; 1\)</span> so increasing heart volume increases the hazard. A 95% confidence interval for the hazard ratio is (1.05, 1.12) so every 1 cm<span class="math inline">\(^3\)</span> increase in heart volume increases the hazard by between 5% and 12%</p></li>
<li><p><strong>Diet:</strong> <span class="math inline">\((1.28/0.58)^2+(0.41/0.59)^2=5.3\)</span> and the 95th percentile of the <span class="math inline">\(\chi^2_2\)</span> distribution is 5.99 (2 degrees of freedom since <span class="math inline">\(k=3\)</span>). Since 5.3 &lt; 5.99 there isn’t significant evidence, at the 5% level of test, that diet affects hazards.</p></li>
</ul>
<p>Our data suggest that neither age, digitalisation nor sex appear to affect hazard at the 5% level of significance. This is <strong>not</strong> the same as saying that they have no effect. For example, the 95% confidence interval for <span class="math inline">\(e^{\beta_7}\)</span> is <span class="math inline">\((0.83, 6.18)\)</span> so that the hazard for men could be a fourth fifths that for women or more than six times as much so there <strong>could</strong> be a large difference in hazards between M &amp; F. These data exclude neither possibility at the 95% confidence level. Ideally we would like more data to reduce the width of this interval.</p>
<p><strong>Hazard ratios</strong> We have already seen in Equation @ref(eq:phint) how to relate the hazard to the parameters of the proportional hazards model. This enables us to calculate hazard ratios comparing two individuals. For example the hazard ratio comparing</p>
<ul>
<li>25 year old meat-eater on drug treatment A</li>
</ul>
<p>with a</p>
<ul>
<li>75 year old vegan on drug treatment B</li>
</ul>
<p>is given by <span class="math display">\[\begin{align*}
  \frac{h(t; x_1=0, x_2 = -20, x_4 = 1)}{h(t; x_1=1, x_2 = 30, x_4 = 0)}&amp;=\frac{h_0(t)exp(0 -0.03 \times -20 + 1.28)}{h_0(t)exp(-2.10 -0.03 \times 30 + 0)}  \\
   &amp;=\frac{exp(1.88)}{exp(-3.00)} \\
   &amp;=exp(4.88)\\
   &amp;\approx 132
\end{align*}\]</span></p>
<p>So the 25 year old meat-eater on drug treatment A has a hazard which is 132 times greater than the 75 year old vegan on drug treatment B.</p>
</section>
<section id="including-interaction-terms" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="including-interaction-terms"><span class="header-section-number">6.5</span> Including interaction terms</h2>
<p>Suppose that we wanted to investigate the interaction between the two binary variables <strong>treatment</strong> and <strong>sex</strong>. Then we would handle this by creating a new variable e.g.&nbsp; <span class="math display">\[
x_7 = x_1 \times x_6,
\]</span> the product of the treatment and sex variables. Since <span class="math inline">\(x_1=0\)</span> for treatment A and <span class="math inline">\(x_1=1\)</span> for treatment B, if follows that <span class="math inline">\(x_7=0\)</span> for all subjects receiving A and <span class="math inline">\(x_7=x_6\)</span> for those receiving treatment B. The hazards for the interaction model, by treatment, are <span class="math display">\[\begin{align}
h(t;x) &amp;= h_0(t) e^{\beta_2 x_2 + \beta_3 x_3 +  \beta_4 x_4 + \beta_5 x_5  + \beta_6 x_6} &amp; \quad \textrm{for treatment A} \\
h(t;x) &amp;= h_0(t) e^{\beta_1 + \beta_2 x_2 +  \beta_3 x_3 +  \beta_4 x_4 + \beta_5 x_5  + (\beta_6 + \beta_7) x_6 } &amp; \quad \textrm{for treatment B}
\end{align}\]</span> where <span class="math inline">\(\beta_7\)</span> reflects the interaction effect. Interactions involving a <span class="math inline">\(k\)</span>-level factor are handled by converting the factor into <span class="math inline">\(k-1\)</span> dummy binary variables. There are</p>
<ul>
<li><p><span class="math inline">\(k-1\)</span> degrees of freedom for an interaction between a <span class="math inline">\(k\)</span>-level factor and a continuous covariate</p></li>
<li><p><span class="math inline">\((k-1)(j-1)\)</span> degrees of freedom for an interaction between a <span class="math inline">\(k\)</span>-level and a <span class="math inline">\(j\)</span>-level factor.</p></li>
</ul>
<p>The separate parts of the <span class="math inline">\(\chi^2\)</span> statistic are added to assess significance.</p>
</section>
<section id="model-checking" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="model-checking"><span class="header-section-number">6.6</span> Model Checking</h2>
<p>Whenever fitting a proportional hazards model, it is important to check the proportional hazards assumption i.e.&nbsp;that for covariates <span class="math inline">\(\mathbf{x}\)</span> relative to the baseline where <span class="math inline">\(\mathbf{x} = 0\)</span>, <span class="math display">\[h(t; x) =   e^{\boldsymbol{\beta}' \mathbf{x}} h_0(t).\]</span> Typically this is done in two ways:</p>
<ul>
<li><p>Log-log plots</p></li>
<li><p>Residual plots</p></li>
</ul>
<p>If these diagnostic tests fails and it is concluded that a proportional hazards model is not appropriate then there are two options. One is in the special case where proportionality only breaks down for one particular factor in which case a stratified proportional hazards model might be considered. The other option is to consider a parametric AFT model which does not have the proportional hazards property i.e.&nbsp;not Weibull or Exponential.</p>
<section id="log-log-plots-for-factor-variables" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="log-log-plots-for-factor-variables"><span class="header-section-number">6.6.1</span> Log-Log Plots for Factor Variables</h3>
<p>Suppose that we have two treatments and we wish to test the proportional hazards assumption between these two treatments. We have defined an indicator variable <span class="math inline">\(x_1\)</span> so that <span class="math display">\[x_1 = \left\{ \begin{array}{rl}
                0 &amp; \textrm{if treatment A} \\
                1 &amp; \textrm{if treatment B}
               \end{array} \right. \\
\]</span> Then modelling via proportional hazards <span class="math display">\[h(t; x) =   e^{\boldsymbol{\beta}' \mathbf{x}} h_0(t).\]</span> so for treatment A we have hazard <span class="math inline">\(h(t; 0) =  h_0(t)\)</span> while for treatment B we have <span class="math inline">\(h(t; 1) =   e^{\boldsymbol{\beta}} h_0(t)\)</span>. Now, noting that <span class="math inline">\(S(t) = \exp \left\{ -\int_0^t h(t) dt \right\}\)</span> we find <span class="math display">\[\begin{align}
- \log S_A(t) &amp;= \int_0^t h(t) \, dt \\
- \log S_B(t) &amp;= e^\beta \int_0^t h(t) \, dt \\
\Rightarrow \log [ - \log S_B(t)  ] &amp;= \beta +  \log [ - \log S_A(t)  ]
\end{align}\]</span> so, if we plot an estimate of <span class="math inline">\(\log [ - \log S_j(t) ]\)</span> against <span class="math inline">\(t\)</span> for both treatments we should get parallel curves a distance <span class="math inline">\(\beta\)</span> apart. If the curves cross then a proportional hazards model is not appropriate.</p>
</section>
<section id="log-log-implementation-in-r" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="log-log-implementation-in-r"><span class="header-section-number">6.6.2</span> Log-Log Implementation in <span class="math inline">\(R\)</span></h3>
<p>To produce separate log-log survival plots for different levels of a factor variable you can use the <code>strata</code> function within the model specification of the <code>coxph</code> function. The proportional hazards model is then fitted within each level of the factor. For example, for the lymphoma data where there are two levels of the <code>stage</code> variable we write</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"datasets/lymphoma.Rdata"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lym_sv <span class="ot">&lt;-</span> <span class="fu">Surv</span>(lymphoma<span class="sc">$</span>time, lymphoma<span class="sc">$</span>censor, <span class="at">type =</span> <span class="st">"right"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>lym_ph <span class="ot">&lt;-</span> <span class="fu">coxph</span>(lym_sv <span class="sc">~</span> <span class="fu">strata</span>(lymphoma<span class="sc">$</span>stage))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>survminer<span class="sc">::</span><span class="fu">ggsurvplot</span>(<span class="fu">survfit</span>(lym_ph), <span class="at">fun =</span> <span class="st">"cloglog"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span>  lymphoma,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">300</span>),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">xlab =</span> <span class="st">"Time (weeks)"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">legend.labs =</span> <span class="fu">c</span>(<span class="st">"Stage 3"</span>, <span class="st">"Stage 4"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lymKM" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lymKM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="proportionalhazards_files/figure-html/fig-lymKM-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lymKM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Log-log survival curves by lymphoma stage
</figcaption>
</figure>
</div>
</div>
</div>
<p>The evidence for proportional hazards in <a href="#fig-lymKM" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> is inconclusive. There is some crossing but it isn’t extensive. This is a small dataset from which it is hard to draw meaningful conclusions.</p>
</section>
<section id="residual-plots" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="residual-plots"><span class="header-section-number">6.6.3</span> Residual Plots</h3>
<p>Various types of residuals can be defined for survival regression models. One choice we will discuss briefly are the Schoenfeld Residuals. Schoenfeld residuals are defined only for non-censored observations and there is a separate set for each of the covariates. They are the difference between the value of the covariate of interest for the subject experiencing the event (say death) and the expectation over all members of the risk set of the covariate: <span class="math display">\[
r_{ik} = x_{ik} - \sum_{j \in \mathcal{R}(t_{i})} x_{jk} \hat{p}_j,
\]</span> where <span class="math inline">\(r_{ik}\)</span> is the Schoenfeld residual for individual <span class="math inline">\(i\)</span> for the <span class="math inline">\(k^{th}\)</span> covariate, <span class="math inline">\(x_{jk}\)</span> are the values for that covariate for the individuals <span class="math inline">\(j\)</span> in the risk set for <span class="math inline">\(\mathcal{R}(t_{i})\)</span> of individuals at time <span class="math inline">\(t_i\)</span>, the time of death for the <span class="math inline">\(i^{th}\)</span> individual and <span class="math inline">\(\hat{p}_j\)</span> is the estimated probability that the <span class="math inline">\(j^{th}\)</span> person dies by time <span class="math inline">\(t_i\)</span>. These should be independent of time so a plot of these versus time should show no dependence. Deviation from independence will indicate inadequacy of the proportional hazards model.</p>
<p>Schoenfeld residuals can be obtained as follows (using the atrial fibrillation example <code>afibph</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>schoenfeld_resid <span class="ot">&lt;-</span> <span class="fu">resid</span>(afibph, <span class="at">type =</span> <span class="st">"schoenfeld"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This produces an array with one column per covariate. The function <code>cox.zph()</code> can be used to show plots of residuals against time, and implement hypothesis test of no association with time, but we will not study the use of this function in this module.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Cox, D.R. (1972), Regression Models and Life-Tables. Journal of the Royal Statistical Society: Series B (Methodological), 34: 187-202. <a href="https://doi.org/10.1111/j.2517-6161.1972.tb00899.x">https://doi.org/10.1111/j.2517-6161.1972.tb00899.x</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Cox, D. R. (1975). Partial Likelihood. Biometrika, 62(2), 269–276. <a href="https://doi.org/10.2307/2335362">https://doi.org/10.2307/2335362</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./aft.html" class="pagination-link" aria-label="Accelerated Failure Time (AFT) Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Accelerated Failure Time (AFT) Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>