<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Multiple independent variables | MAS5052 Part 2: Likelihood and Linear Models</title>
  <meta name="description" content="Lecture notes for MAS5052" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Multiple independent variables | MAS5052 Part 2: Likelihood and Linear Models" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Lecture notes for MAS5052" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Multiple independent variables | MAS5052 Part 2: Likelihood and Linear Models" />
  
  <meta name="twitter:description" content="Lecture notes for MAS5052" />
  

<meta name="author" content="Jeremy Oakley" />


<meta name="date" content="2022-07-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="qualitative-independent-variables.html"/>
<link rel="next" href="using-linear-models-for-prediction.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MAS5052 Part 2</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About these notes</a></li>
<li class="part"><span><b>I Likelihood methods</b></span></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducing likelihood methods</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#recap-maximising-functions"><i class="fa fa-check"></i><b>1.1</b> Recap: maximising functions</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#maximum-likelihood-estimation-a-first-example"><i class="fa fa-check"></i><b>1.2</b> Maximum likelihood estimation: a first example</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducing-the-likelihood-function.html"><a href="introducing-the-likelihood-function.html"><i class="fa fa-check"></i><b>2</b> Introducing the likelihood function</a></li>
<li class="chapter" data-level="3" data-path="models-and-data.html"><a href="models-and-data.html"><i class="fa fa-check"></i><b>3</b> Models and data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="models-and-data.html"><a href="models-and-data.html#data-notation"><i class="fa fa-check"></i><b>3.1</b> Data: notation</a></li>
<li class="chapter" data-level="3.2" data-path="models-and-data.html"><a href="models-and-data.html#models-and-parameters"><i class="fa fa-check"></i><b>3.2</b> Models and parameters</a></li>
<li class="chapter" data-level="3.3" data-path="models-and-data.html"><a href="models-and-data.html#likelihood-functions-for-i.i.d-data"><i class="fa fa-check"></i><b>3.3</b> Likelihood functions for i.i.d data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html"><i class="fa fa-check"></i><b>4</b> Maximisation techniques</a>
<ul>
<li class="chapter" data-level="4.1" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#log-likelihood"><i class="fa fa-check"></i><b>4.1</b> Log-likelihood</a></li>
<li class="chapter" data-level="4.2" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#discrete-parameters"><i class="fa fa-check"></i><b>4.2</b> Discrete parameters</a></li>
<li class="chapter" data-level="4.3" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#multi-parameter-problems"><i class="fa fa-check"></i><b>4.3</b> Multi-parameter problems</a></li>
<li class="chapter" data-level="4.4" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#using-a-computer"><i class="fa fa-check"></i><b>4.4</b> Using a computer</a></li>
<li class="chapter" data-level="4.5" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#a-warning-example"><i class="fa fa-check"></i><b>4.5</b> A warning example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><i class="fa fa-check"></i><b>5</b> Likelihood for confidence intervals and hypothesis tests</a>
<ul>
<li class="chapter" data-level="5.1" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#confidence-intervals"><i class="fa fa-check"></i><b>5.1</b> Confidence intervals</a></li>
<li class="chapter" data-level="5.2" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#hypothesis-tests"><i class="fa fa-check"></i><b>5.2</b> Hypothesis tests</a></li>
<li class="chapter" data-level="5.3" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#a-more-formal-approach"><i class="fa fa-check"></i><b>5.3</b> A more formal approach</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#asymptotic-normality-of-the-maximum-likelihood-estimator"><i class="fa fa-check"></i><b>5.3.1</b> Asymptotic normality of the maximum likelihood estimator</a></li>
<li class="chapter" data-level="5.3.2" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#confidence-intervals-based-on-asymptotic-normality"><i class="fa fa-check"></i><b>5.3.2</b> Confidence intervals based on asymptotic normality</a></li>
<li class="chapter" data-level="5.3.3" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#the-generalised-likelihood-ratio-test"><i class="fa fa-check"></i><b>5.3.3</b> The generalised likelihood ratio test</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Linear Models</b></span></li>
<li class="chapter" data-level="6" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html"><i class="fa fa-check"></i><b>6</b> Introducing linear models</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#example-relationship-between-temperature-and-ozone"><i class="fa fa-check"></i><b>6.1</b> Example: relationship between temperature and ozone</a></li>
<li class="chapter" data-level="6.2" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#notation-and-terminology"><i class="fa fa-check"></i><b>6.2</b> Notation and terminology</a></li>
<li class="chapter" data-level="6.3" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#example-suspected-electoral-fraud"><i class="fa fa-check"></i><b>6.3</b> Example: suspected electoral fraud</a></li>
<li class="chapter" data-level="6.4" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#definition-of-a-linear-model"><i class="fa fa-check"></i><b>6.4</b> Definition of a linear model</a></li>
<li class="chapter" data-level="6.5" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#the-simple-linear-regression-model"><i class="fa fa-check"></i><b>6.5</b> The simple linear regression model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="parameter-estimation.html"><a href="parameter-estimation.html"><i class="fa fa-check"></i><b>7</b> Parameter estimation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="parameter-estimation.html"><a href="parameter-estimation.html#least-squares-estimation"><i class="fa fa-check"></i><b>7.1</b> Least squares estimation</a></li>
<li class="chapter" data-level="7.2" data-path="parameter-estimation.html"><a href="parameter-estimation.html#assumptions-for-least-squares"><i class="fa fa-check"></i><b>7.2</b> Assumptions for least squares</a></li>
<li class="chapter" data-level="7.3" data-path="parameter-estimation.html"><a href="parameter-estimation.html#relationship-with-maximum-likelihood-estimation"><i class="fa fa-check"></i><b>7.3</b> Relationship with maximum likelihood estimation</a></li>
<li class="chapter" data-level="7.4" data-path="parameter-estimation.html"><a href="parameter-estimation.html#estimating-sigma2"><i class="fa fa-check"></i><b>7.4</b> Estimating <span class="math inline">\(\sigma^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html"><i class="fa fa-check"></i><b>8</b> Matrix notation for linear models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#least-squares-estimates-in-matrix-form"><i class="fa fa-check"></i><b>8.1</b> Least squares estimates in matrix form</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#example-fitting-a-polynomial-regression-model"><i class="fa fa-check"></i><b>8.1.1</b> Example: fitting a polynomial regression model</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#estimate-of-sigma2-in-matrix-form"><i class="fa fa-check"></i><b>8.2</b> Estimate of <span class="math inline">\(\sigma^2\)</span> in matrix form</a></li>
<li class="chapter" data-level="8.3" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#derivation-of-hatbeta"><i class="fa fa-check"></i><b>8.3</b> Derivation of <span class="math inline">\(\hat{\beta}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="fitting-a-linear-model-in-r.html"><a href="fitting-a-linear-model-in-r.html"><i class="fa fa-check"></i><b>9</b> Fitting a linear model in R</a>
<ul>
<li class="chapter" data-level="9.1" data-path="fitting-a-linear-model-in-r.html"><a href="fitting-a-linear-model-in-r.html#plotting-a-fitted-regression-line"><i class="fa fa-check"></i><b>9.1</b> Plotting a fitted regression line</a></li>
<li class="chapter" data-level="9.2" data-path="fitting-a-linear-model-in-r.html"><a href="fitting-a-linear-model-in-r.html#the-summary-command"><i class="fa fa-check"></i><b>9.2</b> The <code>summary()</code> command</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html"><i class="fa fa-check"></i><b>10</b> Qualitative independent variables</a>
<ul>
<li class="chapter" data-level="10.1" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#example-cancer-survival-data"><i class="fa fa-check"></i><b>10.1</b> Example: cancer survival data</a></li>
<li class="chapter" data-level="10.2" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#a-linear-model-for-the-cancer-data"><i class="fa fa-check"></i><b>10.2</b> A linear model for the cancer data</a></li>
<li class="chapter" data-level="10.3" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#notation-for-qualitative-independent-variables"><i class="fa fa-check"></i><b>10.3</b> Notation for qualitative independent variables</a></li>
<li class="chapter" data-level="10.4" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#the-one-way-anova-model-in-matrix-form"><i class="fa fa-check"></i><b>10.4</b> The one-way ANOVA model in matrix form</a></li>
<li class="chapter" data-level="10.5" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#least-squares-estimates-for-the-one-way-anova-model"><i class="fa fa-check"></i><b>10.5</b> Least squares estimates for the one-way ANOVA model</a></li>
<li class="chapter" data-level="10.6" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#fitting-a-one-way-anova-model-in-r"><i class="fa fa-check"></i><b>10.6</b> Fitting a one-way ANOVA model in R</a></li>
<li class="chapter" data-level="10.7" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#an-alternative-parameterisation"><i class="fa fa-check"></i><b>10.7</b> An alternative parameterisation</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-independent-variables.html"><a href="multiple-independent-variables.html"><i class="fa fa-check"></i><b>11</b> Multiple independent variables</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multiple-independent-variables.html"><a href="multiple-independent-variables.html#causation-versus-association"><i class="fa fa-check"></i><b>11.1</b> Causation versus association</a></li>
<li class="chapter" data-level="11.2" data-path="multiple-independent-variables.html"><a href="multiple-independent-variables.html#analysis-of-covariance"><i class="fa fa-check"></i><b>11.2</b> Analysis of Covariance</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="using-linear-models-for-prediction.html"><a href="using-linear-models-for-prediction.html"><i class="fa fa-check"></i><b>12</b> Using linear models for prediction</a>
<ul>
<li class="chapter" data-level="12.1" data-path="using-linear-models-for-prediction.html"><a href="using-linear-models-for-prediction.html#obtaining-predictions-in-r"><i class="fa fa-check"></i><b>12.1</b> Obtaining predictions in R</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MAS5052 Part 2: Likelihood and Linear Models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-independent-variables" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Multiple independent variables<a href="multiple-independent-variables.html#multiple-independent-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<script type="text/javascript">
$(document).ready(function() {
  $folds = $(".fold");
  $folds.wrapInner("<div class=\"fold-blck\">"); // wrap a div container around content
  $folds.prepend("<button class=\"fold-btn\">Show solution</button>");  // add a button
  $(".fold-blck").toggle();  // fold all blocks
  $(".fold-btn").on("click", function() {  // add onClick event
    $(this).text($(this).text() === "Show solution" ? "Hide solution" : "Show solution");  // if the text equals "Fold", change it to "Unfold"or else to "Fold" 
    $(this).next(".fold-blck").toggle("linear");  // "swing" is the default easing function. This can be further customized in its speed or the overall animation itself.
  })
});
</script>
<p>Recall the <a href="http://www.jeremy-oakley.staff.shef.ac.uk/notes/datascience/exploratory-data-analysis-using-r.html#case-study-what-makes-a-country-good-at-maths">PISA maths test data from Semester 1</a>. Here, our dependent variable was a country’s maths test score, and we had multiple independent variables: gdp, income inequality (gini coefficient), homework hours, and school starting age.</p>
<p>We’ll now look at how to incorporate multiple independent variables in a linear model.</p>
<div class="rmdnote" latex-info="">
<p>If the main interest is in, say, the effect of gdp, incorporating the variables enables us to assess the effect of gdp, whilst accounting for (sometimes described as “adjusting for” or “controlling for”) possible effects of other variables.</p>
</div>
<p>We’ll first import the data, and create one extra column (<code>wealthiest</code>): a binary variable that indicates whether a country as a <code>gdp</code> higher and 17000.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="multiple-independent-variables.html#cb48-1" aria-hidden="true" tabindex="-1"></a>maths <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;http://www.jeremy-oakley.staff.shef.ac.uk/mas113/maths.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="multiple-independent-variables.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wealthiest =</span> gdp <span class="sc">&gt;</span> <span class="dv">17000</span>)</span>
<span id="cb48-3"><a href="multiple-independent-variables.html#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(maths)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 8
##   country         continent     score   gdp  gini homework start.age wealthiest
##   &lt;chr&gt;           &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;     
## 1 Albania         Europe          413  4147  29        5.1         6 FALSE     
## 2 Algeria         Africa          360  3844  27.6     NA           6 FALSE     
## 3 Argentina       South America   409 12449  42.7      3.7         6 FALSE     
## 4 Australia       Oceanea         494 49928  34.7      6           5 TRUE      
## 5 Austria         Europe          497 44177  30.5      4.5         6 TRUE      
## 6 B-S-J-G (China) Asia            531  8123  42.2     13.8         6 FALSE</code></pre>
<p>For illustration, we’ll treat <code>start.age</code> as a factor variable with three levels, and consider modelling the effects of <code>gdp</code>, <code>gini</code>, <code>homework</code> and <code>factor(start.age)</code> on <code>score</code>. How might we write down such a model?</p>
<div class="rmdnote" latex-info="">
<p>When thinking about suitable notation:</p>
<ul>
<li>use one letter for each quantitative independent variable;</li>
<li>use one <em>additional subscript</em> for each qualitative independent variable.</li>
</ul>
</div>
<p>We imagine splitting the data up into three groups:</p>
<ul>
<li>group <span class="math inline">\(i=1\)</span> for countries with a <code>start.age</code> of 5;</li>
<li>group <span class="math inline">\(i=2\)</span> for countries with a <code>start.age</code> of 6;</li>
<li>group <span class="math inline">\(i=3\)</span> for countries with a <code>start.age</code> of 7.</li>
</ul>
<p>Then, for the <span class="math inline">\(j\)</span>-th observation (country) within group <span class="math inline">\(i\)</span>, define</p>
<ul>
<li><span class="math inline">\(Y_{ij}\)</span> to be the country’s score;</li>
<li><span class="math inline">\(w_{ij}\)</span> to be the country’s gdp;</li>
<li><span class="math inline">\(x_{ij}\)</span> to be the country’s gini coefficient;</li>
<li><span class="math inline">\(z_{ij}\)</span> to be the mean number of homework hours per week in that country.</li>
</ul>
We can now write the model as
<span class="math display">\[
Y_{ij} = \mu + \tau_i + \beta_1 w_{ij} + \beta_2 x_{ij} + \beta_3z_{ij}+ \varepsilon_{ij},
\]</span>
with <span class="math inline">\(\varepsilon_{ij}\sim N(0, \sigma^2)\)</span>. This model is overparameterised, so we apply the constraint <span class="math inline">\(\tau_1 = 0\)</span>.
<div class="rmdnote">
<p>
We interpret <span class="math inline"><span class="math inline">\(\tau_i\)</span></span>, for <span class="math inline"><span class="math inline">\(i=2\)</span></span> (or 3) as the difference in mean score between two countries with identical values of <code>gdp</code>, <code>gini</code> and <code>homework</code>, but in which one has a school <code>start.age</code> of 6 (or 7) and one with a school <code>start.age</code> of 5.
</p>
</div>
<p>We fit the model in R as follows:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="multiple-independent-variables.html#cb50-1" aria-hidden="true" tabindex="-1"></a>lmMaths <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> gdp <span class="sc">+</span> gini <span class="sc">+</span> homework <span class="sc">+</span> <span class="fu">factor</span>(start.age), maths)</span>
<span id="cb50-2"><a href="multiple-independent-variables.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmMaths)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ gdp + gini + homework + factor(start.age), 
##     data = maths)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -61.398 -17.884  -0.204  17.867  69.026 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         4.827e+02  3.743e+01  12.896  &lt; 2e-16 ***
## gdp                 1.025e-03  2.181e-04   4.701 2.07e-05 ***
## gini               -2.634e+00  6.939e-01  -3.796 0.000399 ***
## homework            8.343e+00  2.337e+00   3.569 0.000802 ***
## factor(start.age)6  3.062e+00  1.971e+01   0.155 0.877183    
## factor(start.age)7  1.023e+01  2.118e+01   0.483 0.630987    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 31.31 on 50 degrees of freedom
##   (14 observations deleted due to missingness)
## Multiple R-squared:  0.5947, Adjusted R-squared:  0.5542 
## F-statistic: 14.67 on 5 and 50 DF,  p-value: 7.547e-09</code></pre>
<p>We read off from this <span class="math inline">\(\hat{\mu}=482.7\)</span>, <span class="math inline">\(\hat{\tau}_2= 3.06\)</span>, <span class="math inline">\(\hat{\tau}_3=10.23\)</span>, <span class="math inline">\(\hat{\beta}_1=0.001\)</span>, <span class="math inline">\(\hat{\beta}_2=-2.634\)</span>, and <span class="math inline">\(\hat{\beta}_3=8.343\)</span>.</p>
<div id="causation-versus-association" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Causation versus association<a href="multiple-independent-variables.html#causation-versus-association" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose we were interested in the effect of <code>gdp</code> only. Let’s try fitting the model with this independent variable only:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="multiple-independent-variables.html#cb52-1" aria-hidden="true" tabindex="-1"></a>lmMathsGDP <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> gdp , maths)</span>
<span id="cb52-2"><a href="multiple-independent-variables.html#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmMathsGDP)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ gdp, data = maths)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -105.932  -27.488    5.583   25.925   95.609 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 4.239e+02  7.975e+00  53.153  &lt; 2e-16 ***
## gdp         1.417e-03  2.322e-04   6.101 5.67e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 43.18 on 68 degrees of freedom
## Multiple R-squared:  0.3537, Adjusted R-squared:  0.3442 
## F-statistic: 37.22 on 1 and 68 DF,  p-value: 5.667e-08</code></pre>
<p>Notice how the slope estimate for <code>gdp</code> has changed from that in <code>lmMaths</code>: it has increased by about 50% to 0.00147. Two points to note are</p>
<ol style="list-style-type: decimal">
<li><code>gdp</code> and <code>gini</code> are correlated. This means that removing <code>gini</code> from the model is likely to change the estimated slope for <code>gdp</code>. This is something we try to avoid, if we can <em>design</em> the experiment (i.e. we can choose the values of the independent variables.)</li>
<li>If we are hoping to learn a <em>causal</em> relationship between <code>gdp</code> and <code>score</code>, we need to include other variables in the model which may also effect <code>score</code>. If these other variables are omitted, we are (potentially) instead learning about the <em>association</em> between <code>gdp</code> and <code>score</code>. An interpretation of this is as follows.
<ul>
<li><code>lmMaths</code> tells us that when we increase <code>gdp</code> by one unit, <em>and all other variables stay the same</em>, we expect <code>score</code> to increase by 0.001 units. If we were confident that all other relevant variables were unchanged, the change in <code>score</code> must be caused by the change in <code>gdp</code>.</li>
<li><code>lmMathsGDP</code> (together with our knowledge of the correlation of <code>gdp</code> and <code>gini</code>) tells us that when we increase <code>gdp</code> by one unit, we expect other variables such as <code>gini</code> to change. The combined change in <em>all</em> these variables means that we expect <code>score</code> to increase by 0.0014 units. We cannot necessarily attribute the change in <code>score</code> to the change in <code>gpd</code>: it might have been caused by another variables changing.</li>
</ul></li>
</ol>
</div>
<div id="analysis-of-covariance" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Analysis of Covariance<a href="multiple-independent-variables.html#analysis-of-covariance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall this plot we produced in <a href="http://www.jeremy-oakley.staff.shef.ac.uk/notes/datascience/exploratory-data-analysis-using-r.html#scatter-plots-to-represent-three-variables">Semester 1, Chapter 1</a>:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="multiple-independent-variables.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(maths, <span class="fu">aes</span>(<span class="at">x =</span> gini, <span class="at">y =</span> score, <span class="at">colour =</span> wealthiest))<span class="sc">+</span></span>
<span id="cb54-2"><a href="multiple-independent-variables.html#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb54-3"><a href="multiple-independent-variables.html#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<p><img src="MAS5052-Part2_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<p>We have two fitted regression lines: one for the group <code>wealthiest == TRUE</code> (countries with <code>gdp</code><span class="math inline">\(&gt;17000\)</span>), and one for the remaining countries. This sort of modelling with multiple regression lines is sometimes referred to as <strong>Analysis of Covariance</strong> (ANCOVA). The emphasis is usually on comparing means between groups, adjusting for different values of covariates between groups.</p>
<p>We will now consider how we would write down this model, and how to fit it in R.
Again, the idea is to use an extra subscript for the qualitative variable (<code>wealthiest</code>): define <span class="math inline">\(Y_{ij}\)</span> to be the <code>score</code> for the <span class="math inline">\(j\)</span>th country in group <span class="math inline">\(i\)</span>, where <span class="math inline">\(i=1\)</span> corresponds to <code>wealthiest==FALSE</code> and <span class="math inline">\(i=2\)</span> corresponds to <code>wealthiest==TRUE</code>, with <span class="math inline">\(x_{ij}\)</span> the corresponding <code>gdp</code> value. Our model is
<span class="math display">\[
Y_{ij} = \mu + \tau_i + \beta_i x_{ij} + \varepsilon_{ij}
\]</span>
with <span class="math inline">\(\varepsilon_{ij}\sim N(0,\sigma^2)\)</span>. Again this is overparametrised, so we set <span class="math inline">\(\tau_1=0\)</span>. Note that the slope parameter for <code>gdp</code> depends on whether <code>wealthiest</code> is <code>FALSE</code> or <code>TRUE</code>. We think of this as an <strong>interaction</strong> between <code>gdp</code> and <code>wealthiest</code>. We fit the model in R as follows:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="multiple-independent-variables.html#cb55-1" aria-hidden="true" tabindex="-1"></a>lmMathsWealthiest <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> gini <span class="sc">*</span> wealthiest, maths)</span>
<span id="cb55-2"><a href="multiple-independent-variables.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmMathsWealthiest)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ gini * wealthiest, data = maths)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -84.730 -17.966  -0.595  15.104 113.483 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         492.3368    32.5735  15.115   &lt;2e-16 ***
## gini                 -1.7730     0.8507  -2.084   0.0415 *  
## wealthiestTRUE       75.0248    61.7823   1.214   0.2295    
## gini:wealthiestTRUE  -0.4358     1.8385  -0.237   0.8134    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 36.19 on 59 degrees of freedom
##   (7 observations deleted due to missingness)
## Multiple R-squared:  0.5292, Adjusted R-squared:  0.5053 
## F-statistic: 22.11 on 3 and 59 DF,  p-value: 1.022e-09</code></pre>
<p>We read off <span class="math inline">\(\hat{\mu}=492.3368\)</span>, <span class="math inline">\(\hat{\tau}_2 = 75.0248\)</span> and <span class="math inline">\(\hat{\beta_1} = -1.7730\)</span>.</p>
<p>The row <code>gini:wealthiestTRUE</code> corresponds to the difference <span class="math inline">\(\hat{\beta}_2- \hat{\beta}_1\)</span>, so we read off <span class="math inline">\(\hat{\beta}_2= -1.7730 -0.4358\)</span>.</p>
<p>We’ll try to redraw the plot, to check we’ve interpreted everything correctly! (To see what the default colours are in hex format, try <code>scales::show_col(hue_pal()(2))</code>)</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="multiple-independent-variables.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(maths, <span class="fu">aes</span>(<span class="at">x =</span> gini, <span class="at">y =</span> score, <span class="at">colour =</span> wealthiest))<span class="sc">+</span></span>
<span id="cb57-2"><a href="multiple-independent-variables.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb57-3"><a href="multiple-independent-variables.html#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="sc">-</span><span class="fl">1.773</span>, <span class="at">intercept =</span> <span class="fl">492.3368</span>, <span class="at">col =</span> <span class="st">&quot;#F8766D&quot;</span> )<span class="sc">+</span></span>
<span id="cb57-4"><a href="multiple-independent-variables.html#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="sc">-</span><span class="fl">1.773</span> <span class="sc">-</span> <span class="fl">0.4358</span>, </span>
<span id="cb57-5"><a href="multiple-independent-variables.html#cb57-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">intercept =</span> <span class="fl">492.3368</span> <span class="sc">+</span> <span class="fl">75.0248</span>,</span>
<span id="cb57-6"><a href="multiple-independent-variables.html#cb57-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">&quot;#00BFC4&quot;</span> )</span></code></pre></div>
<p><img src="MAS5052-Part2_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>The formatting of the lines is slightly different, but otherwise this looks correct.</p>
<div class="example">
<p><span id="exm:exampleANCOVA" class="example"><strong>Example 11.1  (Fitting a linear model in R: ANCOVA.) </strong></span><br></p>
</div>
<p>Consider the built in dataset <code>mtcars</code> (see <code>?mtcars</code> for details)</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="multiple-independent-variables.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>We’ll be using the column <code>am</code> which describes transmission type. To make it more readable, we’ll do</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="multiple-independent-variables.html#cb60-1" aria-hidden="true" tabindex="-1"></a>mtcars2 <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb60-2"><a href="multiple-independent-variables.html#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">transmission =</span> <span class="fu">factor</span>(am, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;automatic&quot;</span>,  <span class="st">&quot;manual&quot;</span>)))</span></code></pre></div>
<ol style="list-style-type: decimal">
<li>Fit the following model in R:</li>
</ol>
<p><span class="math display">\[
Y_{ij} = \mu + \tau_i + \beta_i x_{ij} + \varepsilon_{ij}
\]</span>
where <span class="math inline">\(Y_{ij}\)</span> is the fuel economy <code>mpg</code> of the <span class="math inline">\(j\)</span>th car in group <span class="math inline">\(i\)</span>, and <span class="math inline">\(x_{ij}\)</span> is the corresponding weight <code>wt</code>, for <span class="math inline">\(i=1,2\)</span>. Group <span class="math inline">\(i=1\)</span> corresponds to automatic cars, and <span class="math inline">\(i=2\)</span> corresponds to manual cars.</p>
<ol start="2" style="list-style-type: decimal">
<li><p>For a car with weight of 3 units (1000 lbs), what is the expected change in fuel economy from changing from automatic to manual?</p></li>
<li><p>We can plot the fitted model with the commands</p></li>
</ol>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="multiple-independent-variables.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars2, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg, <span class="at">colour =</span> transmission)) <span class="sc">+</span></span>
<span id="cb61-2"><a href="multiple-independent-variables.html#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb61-3"><a href="multiple-independent-variables.html#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="MAS5052-Part2_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>Try to (approximately) redraw this plot, without using <code>geom_smooth()</code>: use <code>geom_abline()</code> instead.</p>
<div class="fold">
<ol style="list-style-type: decimal">
<li>In R we do</li>
</ol>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="multiple-independent-variables.html#cb62-1" aria-hidden="true" tabindex="-1"></a>lmCars <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">*</span> transmission, mtcars2)</span>
<span id="cb62-2"><a href="multiple-independent-variables.html#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmCars)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt * transmission, data = mtcars2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.6004 -1.5446 -0.5325  0.9012  6.0909 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            31.4161     3.0201  10.402 4.00e-11 ***
## wt                     -3.7859     0.7856  -4.819 4.55e-05 ***
## transmissionmanual     14.8784     4.2640   3.489  0.00162 ** 
## wt:transmissionmanual  -5.2984     1.4447  -3.667  0.00102 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.591 on 28 degrees of freedom
## Multiple R-squared:  0.833,  Adjusted R-squared:  0.8151 
## F-statistic: 46.57 on 3 and 28 DF,  p-value: 5.209e-11</code></pre>
<p>From this, we read off <span class="math inline">\(\hat{\mu}=31.4161\)</span>, <span class="math inline">\(\hat{\beta}_1=-3.7859\)</span>, <span class="math inline">\(\hat{\tau}_2=14.8784\)</span>, <span class="math inline">\(\hat{\beta}_2=-3.7859 -5.2984\)</span>.</p>
<ol start="2" style="list-style-type: decimal">
<li>An automatic car with weight 3 units has estimated expected <code>mgp</code>:
<span class="math display">\[
E(Y) = \hat{\mu} +\hat{\beta}_1\times 3= 31.4161 -3.7859 \times 3 = 20.0584
\]</span>
If the car changes from automatic to manual, the estimated expected <code>mgp</code> is
<span class="math display">\[
\hat{\mu} +\hat{\tau}_2 +\hat{\beta}_2\times 3
\]</span>
The change is estimated to be
<span class="math display">\[\hat{\tau}_2 + 3(\hat{\beta}_2 - \hat{\beta}_1) =  14.8784 -5.2984\times 3. \]</span></li>
<li>We (approximately) reproduce the plot with the commands</li>
</ol>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="multiple-independent-variables.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars2, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg, <span class="at">colour =</span> transmission))<span class="sc">+</span></span>
<span id="cb64-2"><a href="multiple-independent-variables.html#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb64-3"><a href="multiple-independent-variables.html#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="sc">-</span><span class="fl">3.7859</span>, <span class="at">intercept =</span> <span class="fl">31.4161</span>, <span class="at">col =</span> <span class="st">&quot;#F8766D&quot;</span> )<span class="sc">+</span></span>
<span id="cb64-4"><a href="multiple-independent-variables.html#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="sc">-</span><span class="fl">3.7859</span> <span class="sc">-</span><span class="fl">5.2984</span>, </span>
<span id="cb64-5"><a href="multiple-independent-variables.html#cb64-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">intercept =</span> <span class="fl">31.4161</span> <span class="sc">+</span> <span class="fl">14.8784</span>,</span>
<span id="cb64-6"><a href="multiple-independent-variables.html#cb64-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">&quot;#00BFC4&quot;</span> )</span></code></pre></div>
<p><img src="MAS5052-Part2_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="qualitative-independent-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="using-linear-models-for-prediction.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
