<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Qualitative independent variables | MAS5052 Part 2: Likelihood and Linear Models</title>
  <meta name="description" content="Lecture notes for MAS5052" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Qualitative independent variables | MAS5052 Part 2: Likelihood and Linear Models" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Lecture notes for MAS5052" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Qualitative independent variables | MAS5052 Part 2: Likelihood and Linear Models" />
  
  <meta name="twitter:description" content="Lecture notes for MAS5052" />
  

<meta name="author" content="Jeremy Oakley" />


<meta name="date" content="2022-07-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="fitting-a-linear-model-in-r.html"/>
<link rel="next" href="multiple-independent-variables.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MAS5052 Part 2</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About these notes</a></li>
<li class="part"><span><b>I Likelihood methods</b></span></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducing likelihood methods</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#recap-maximising-functions"><i class="fa fa-check"></i><b>1.1</b> Recap: maximising functions</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#maximum-likelihood-estimation-a-first-example"><i class="fa fa-check"></i><b>1.2</b> Maximum likelihood estimation: a first example</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducing-the-likelihood-function.html"><a href="introducing-the-likelihood-function.html"><i class="fa fa-check"></i><b>2</b> Introducing the likelihood function</a></li>
<li class="chapter" data-level="3" data-path="models-and-data.html"><a href="models-and-data.html"><i class="fa fa-check"></i><b>3</b> Models and data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="models-and-data.html"><a href="models-and-data.html#data-notation"><i class="fa fa-check"></i><b>3.1</b> Data: notation</a></li>
<li class="chapter" data-level="3.2" data-path="models-and-data.html"><a href="models-and-data.html#models-and-parameters"><i class="fa fa-check"></i><b>3.2</b> Models and parameters</a></li>
<li class="chapter" data-level="3.3" data-path="models-and-data.html"><a href="models-and-data.html#likelihood-functions-for-i.i.d-data"><i class="fa fa-check"></i><b>3.3</b> Likelihood functions for i.i.d data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html"><i class="fa fa-check"></i><b>4</b> Maximisation techniques</a>
<ul>
<li class="chapter" data-level="4.1" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#log-likelihood"><i class="fa fa-check"></i><b>4.1</b> Log-likelihood</a></li>
<li class="chapter" data-level="4.2" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#discrete-parameters"><i class="fa fa-check"></i><b>4.2</b> Discrete parameters</a></li>
<li class="chapter" data-level="4.3" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#multi-parameter-problems"><i class="fa fa-check"></i><b>4.3</b> Multi-parameter problems</a></li>
<li class="chapter" data-level="4.4" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#using-a-computer"><i class="fa fa-check"></i><b>4.4</b> Using a computer</a></li>
<li class="chapter" data-level="4.5" data-path="maximisation-techniques.html"><a href="maximisation-techniques.html#a-warning-example"><i class="fa fa-check"></i><b>4.5</b> A warning example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><i class="fa fa-check"></i><b>5</b> Likelihood for confidence intervals and hypothesis tests</a>
<ul>
<li class="chapter" data-level="5.1" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#confidence-intervals"><i class="fa fa-check"></i><b>5.1</b> Confidence intervals</a></li>
<li class="chapter" data-level="5.2" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#hypothesis-tests"><i class="fa fa-check"></i><b>5.2</b> Hypothesis tests</a></li>
<li class="chapter" data-level="5.3" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#a-more-formal-approach"><i class="fa fa-check"></i><b>5.3</b> A more formal approach</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#asymptotic-normality-of-the-maximum-likelihood-estimator"><i class="fa fa-check"></i><b>5.3.1</b> Asymptotic normality of the maximum likelihood estimator</a></li>
<li class="chapter" data-level="5.3.2" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#confidence-intervals-based-on-asymptotic-normality"><i class="fa fa-check"></i><b>5.3.2</b> Confidence intervals based on asymptotic normality</a></li>
<li class="chapter" data-level="5.3.3" data-path="likelihood-for-confidence-intervals-and-hypothesis-tests.html"><a href="likelihood-for-confidence-intervals-and-hypothesis-tests.html#the-generalised-likelihood-ratio-test"><i class="fa fa-check"></i><b>5.3.3</b> The generalised likelihood ratio test</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Linear Models</b></span></li>
<li class="chapter" data-level="6" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html"><i class="fa fa-check"></i><b>6</b> Introducing linear models</a>
<ul>
<li class="chapter" data-level="6.1" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#example-relationship-between-temperature-and-ozone"><i class="fa fa-check"></i><b>6.1</b> Example: relationship between temperature and ozone</a></li>
<li class="chapter" data-level="6.2" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#notation-and-terminology"><i class="fa fa-check"></i><b>6.2</b> Notation and terminology</a></li>
<li class="chapter" data-level="6.3" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#example-suspected-electoral-fraud"><i class="fa fa-check"></i><b>6.3</b> Example: suspected electoral fraud</a></li>
<li class="chapter" data-level="6.4" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#definition-of-a-linear-model"><i class="fa fa-check"></i><b>6.4</b> Definition of a linear model</a></li>
<li class="chapter" data-level="6.5" data-path="introducing-linear-models.html"><a href="introducing-linear-models.html#the-simple-linear-regression-model"><i class="fa fa-check"></i><b>6.5</b> The simple linear regression model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="parameter-estimation.html"><a href="parameter-estimation.html"><i class="fa fa-check"></i><b>7</b> Parameter estimation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="parameter-estimation.html"><a href="parameter-estimation.html#least-squares-estimation"><i class="fa fa-check"></i><b>7.1</b> Least squares estimation</a></li>
<li class="chapter" data-level="7.2" data-path="parameter-estimation.html"><a href="parameter-estimation.html#assumptions-for-least-squares"><i class="fa fa-check"></i><b>7.2</b> Assumptions for least squares</a></li>
<li class="chapter" data-level="7.3" data-path="parameter-estimation.html"><a href="parameter-estimation.html#relationship-with-maximum-likelihood-estimation"><i class="fa fa-check"></i><b>7.3</b> Relationship with maximum likelihood estimation</a></li>
<li class="chapter" data-level="7.4" data-path="parameter-estimation.html"><a href="parameter-estimation.html#estimating-sigma2"><i class="fa fa-check"></i><b>7.4</b> Estimating <span class="math inline">\(\sigma^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html"><i class="fa fa-check"></i><b>8</b> Matrix notation for linear models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#least-squares-estimates-in-matrix-form"><i class="fa fa-check"></i><b>8.1</b> Least squares estimates in matrix form</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#example-fitting-a-polynomial-regression-model"><i class="fa fa-check"></i><b>8.1.1</b> Example: fitting a polynomial regression model</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#estimate-of-sigma2-in-matrix-form"><i class="fa fa-check"></i><b>8.2</b> Estimate of <span class="math inline">\(\sigma^2\)</span> in matrix form</a></li>
<li class="chapter" data-level="8.3" data-path="matrix-notation-for-linear-models.html"><a href="matrix-notation-for-linear-models.html#derivation-of-hatbeta"><i class="fa fa-check"></i><b>8.3</b> Derivation of <span class="math inline">\(\hat{\beta}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="fitting-a-linear-model-in-r.html"><a href="fitting-a-linear-model-in-r.html"><i class="fa fa-check"></i><b>9</b> Fitting a linear model in R</a>
<ul>
<li class="chapter" data-level="9.1" data-path="fitting-a-linear-model-in-r.html"><a href="fitting-a-linear-model-in-r.html#plotting-a-fitted-regression-line"><i class="fa fa-check"></i><b>9.1</b> Plotting a fitted regression line</a></li>
<li class="chapter" data-level="9.2" data-path="fitting-a-linear-model-in-r.html"><a href="fitting-a-linear-model-in-r.html#the-summary-command"><i class="fa fa-check"></i><b>9.2</b> The <code>summary()</code> command</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html"><i class="fa fa-check"></i><b>10</b> Qualitative independent variables</a>
<ul>
<li class="chapter" data-level="10.1" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#example-cancer-survival-data"><i class="fa fa-check"></i><b>10.1</b> Example: cancer survival data</a></li>
<li class="chapter" data-level="10.2" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#a-linear-model-for-the-cancer-data"><i class="fa fa-check"></i><b>10.2</b> A linear model for the cancer data</a></li>
<li class="chapter" data-level="10.3" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#notation-for-qualitative-independent-variables"><i class="fa fa-check"></i><b>10.3</b> Notation for qualitative independent variables</a></li>
<li class="chapter" data-level="10.4" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#the-one-way-anova-model-in-matrix-form"><i class="fa fa-check"></i><b>10.4</b> The one-way ANOVA model in matrix form</a></li>
<li class="chapter" data-level="10.5" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#least-squares-estimates-for-the-one-way-anova-model"><i class="fa fa-check"></i><b>10.5</b> Least squares estimates for the one-way ANOVA model</a></li>
<li class="chapter" data-level="10.6" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#fitting-a-one-way-anova-model-in-r"><i class="fa fa-check"></i><b>10.6</b> Fitting a one-way ANOVA model in R</a></li>
<li class="chapter" data-level="10.7" data-path="qualitative-independent-variables.html"><a href="qualitative-independent-variables.html#an-alternative-parameterisation"><i class="fa fa-check"></i><b>10.7</b> An alternative parameterisation</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-independent-variables.html"><a href="multiple-independent-variables.html"><i class="fa fa-check"></i><b>11</b> Multiple independent variables</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multiple-independent-variables.html"><a href="multiple-independent-variables.html#causation-versus-association"><i class="fa fa-check"></i><b>11.1</b> Causation versus association</a></li>
<li class="chapter" data-level="11.2" data-path="multiple-independent-variables.html"><a href="multiple-independent-variables.html#analysis-of-covariance"><i class="fa fa-check"></i><b>11.2</b> Analysis of Covariance</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="using-linear-models-for-prediction.html"><a href="using-linear-models-for-prediction.html"><i class="fa fa-check"></i><b>12</b> Using linear models for prediction</a>
<ul>
<li class="chapter" data-level="12.1" data-path="using-linear-models-for-prediction.html"><a href="using-linear-models-for-prediction.html#obtaining-predictions-in-r"><i class="fa fa-check"></i><b>12.1</b> Obtaining predictions in R</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MAS5052 Part 2: Likelihood and Linear Models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="qualitative-independent-variables" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Qualitative independent variables<a href="qualitative-independent-variables.html#qualitative-independent-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<script type="text/javascript">
$(document).ready(function() {
  $folds = $(".fold");
  $folds.wrapInner("<div class=\"fold-blck\">"); // wrap a div container around content
  $folds.prepend("<button class=\"fold-btn\">Show solution</button>");  // add a button
  $(".fold-blck").toggle();  // fold all blocks
  $(".fold-btn").on("click", function() {  // add onClick event
    $(this).text($(this).text() === "Show solution" ? "Hide solution" : "Show solution");  // if the text equals "Fold", change it to "Unfold"or else to "Fold" 
    $(this).next(".fold-blck").toggle("linear");  // "swing" is the default easing function. This can be further customized in its speed or the overall animation itself.
  })
});
</script>
<div id="example-cancer-survival-data" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Example: cancer survival data<a href="qualitative-independent-variables.html#example-cancer-survival-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The file <code>cancer.csv</code> has data from patients with
advanced cancers of the stomach, bronchus, colon, ovary or breast
were treated with ascorbate. We suppose that this aim is to
determine if patient survival differs with respect to the organ
affected by the cancer. The survival time in days was recorded for
each patient.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="qualitative-independent-variables.html#cb33-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;cancer.csv&quot;</span>)</span>
<span id="cb33-2"><a href="qualitative-independent-variables.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cancer)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   survival organ  
##      &lt;dbl&gt; &lt;chr&gt;  
## 1      124 Stomach
## 2       42 Stomach
## 3       25 Stomach
## 4       45 Stomach
## 5      412 Stomach
## 6       51 Stomach</code></pre>
<p>We can use a box plot to compare the survival times for each type (<code>organ</code>) of cancer patient:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="qualitative-independent-variables.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cancer, <span class="fu">aes</span>(<span class="at">x =</span> organ, <span class="at">y =</span> survival)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="qualitative-independent-variables.html#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="MAS5052-Part2_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>We suppose that the survival time is the dependent variable of interest, which we can treat as continuous as before. But our independent variable, <code>organ</code>, is qualitative. Can we still use a linear model to analyse these data?</p>
</div>
<div id="a-linear-model-for-the-cancer-data" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> A linear model for the cancer data<a href="qualitative-independent-variables.html#a-linear-model-for-the-cancer-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Clearly, it would <em>not</em> make sense to write a model such as
<span class="math display">\[
Y_i=\beta_0 + \beta_1 x_i +\varepsilon_i,
\]</span>
where <span class="math inline">\(Y_i\)</span> is the survival time of the <span class="math inline">\(i\)</span>-th patient and <span class="math inline">\(x_i\)</span> is
the cancer type of the <span class="math inline">\(i\)</span>-th patient, because
the independent variable (cancer type) is a categorical
variable (i.e. it doesn’t make sense to say “survival time <span class="math inline">\(= 50 +3\times\)</span> stomach cancer”). We could write our model as
<span class="math display">\[
Y_i= \beta_1 x_{i,1} + \beta_2 x_{i,2}+\beta_3 x_{i,3}+\beta_4 x_{i,4}+\beta_5 x_{i,5} +\varepsilon_i,
\]</span>
where <span class="math inline">\(x_{i,j} = 1\)</span> if patient had cancer type <span class="math inline">\(j\)</span> (<span class="math inline">\(j=1\)</span> for Breast, <span class="math inline">\(j=2\)</span> for Bronchus and so on) and <span class="math inline">\(x_{i,j} = 0\)</span> otherwise. We say that <span class="math inline">\(x_{i,j}\)</span> is a <strong>dummy variable</strong>. The five dummy variables here ensure that the correct <span class="math inline">\(\beta\)</span> term is selected for each observation. This notation can be a little cumbersome, so we typically write these sorts of models in a different way.</p>
</div>
<div id="notation-for-qualitative-independent-variables" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Notation for qualitative independent variables<a href="qualitative-independent-variables.html#notation-for-qualitative-independent-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Each observation is associated with a particular group, where the group is specified by the value (level) of the qualitative independent variable. The <code>organ</code> variable can be one of five possibilities, so we think the data as being organised in five groups.</p>
<p>We write <span class="math inline">\(Y_{ij}\)</span> as the <span class="math inline">\(j\)</span>-th observation within group <span class="math inline">\(i\)</span>. Let <span class="math inline">\(g\)</span>
be the total number of groups (with <span class="math inline">\(g=5\)</span> in the cancer data). We then have <span class="math inline">\(i=1,\ldots,g\)</span>.</p>
<div class="rmdnote" latex-info="">
<p>Whereas a quantitative independent variable is typically represented by its own letter (e.g. <span class="math inline">\(x_i\)</span>), we typically represent a qualitative independent variable using <em>an additional subscript</em> on the dependent variable.</p>
</div>
<p>Within group <span class="math inline">\(i\)</span> we let <span class="math inline">\(n_i\)</span> be the total number of
observations, so that we have <span class="math inline">\(j=1,\ldots,n_i\)</span>. In the cancer data,
if we call the group of patients with breast cancer group 1, there
are 11 patients in this group, so <span class="math inline">\(n_1=11\)</span>, and the 11
survival times for patients with stomach cancer are denoted
<span class="math inline">\(Y_{1,1},Y_{1,2},\ldots,Y_{1,11}\)</span>. As usual, we think of <span class="math inline">\(Y_{ij}\)</span> as a random variable, and <span class="math inline">\(y_{ij}\)</span> as the observed value of that random variable.</p>
<p>We let <span class="math inline">\(n\)</span> denote the total number of observations, so that <span class="math inline">\(n=\sum_{i=1}^g n_i\)</span>.</p>
<p>Now let <span class="math inline">\(\mu_i\)</span> denote the population mean of the dependent variable
in group <span class="math inline">\(i\)</span>. We can now write a model for the data as follows:
<span class="math display">\[
Y_{ij}=\mu_i + \varepsilon_{ij},
\]</span>
for <span class="math inline">\(i=1,\ldots,g\)</span>, <span class="math inline">\(j=1,\ldots,n_i\)</span> and <span class="math inline">\(\varepsilon_{ij}\sim N(0,\sigma^2)\)</span>.</p>
<div class="rmdnote" latex-info="">
<p>Analysis of data using this model is sometimes referred to as <strong>one-way analysis of variance</strong> (ANOVA), and we will refer to the above model as the one-way ANOVA model.</p>
</div>
</div>
<div id="the-one-way-anova-model-in-matrix-form" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> The one-way ANOVA model in matrix form<a href="qualitative-independent-variables.html#the-one-way-anova-model-in-matrix-form" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The model
<span class="math display">\[ Y_{ij}=\mu_i + \varepsilon_{ij},\]</span>
for <span class="math inline">\(i=1,\ldots,g\)</span>, <span class="math inline">\(j=1,\ldots,n_i\)</span> is written in matrix form as
<span class="math display">\[
\mathbf{Y} = X\boldsymbol{\beta} + \boldsymbol{\varepsilon},
\]</span>
with
<span class="math display">\[
\mathbf{Y}=\left(\begin{array}{c}Y_{1,1} \\ \vdots \\ Y_{1,n_1} \\ Y_{2,1}\\
\vdots \\ Y_{2,n_2}  \\ \vdots  \\ Y_{g,1} \\
\vdots
\\ Y_{g,n_g}\end{array}\right),\quad
X=\left(\begin{array}{ccccc}1&amp; 0 &amp; 0  &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1&amp; 0 &amp; 0 &amp; \ldots &amp; 0 \\ 0&amp; 1 &amp; 0  &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
0&amp; 1 &amp; 0 &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots   \\ 0&amp; 0 &amp; 0  &amp; \ldots &amp; 1 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
0&amp; 0 &amp; 0 &amp; \ldots &amp; 1
\end{array}\right),\quad
\boldsymbol{\beta}=\left(\begin{array}{c}\mu_1 \\ \vdots \\
\mu_g\end{array}\right),\quad
\boldsymbol{\varepsilon}=\left(\begin{array}{c}\varepsilon_{1,1} \\ \vdots \\ \varepsilon_{1,n_1} \\ \varepsilon_{2,1}\\
\vdots \\ \varepsilon_{2,n_2}  \\ \vdots  \\ \varepsilon_{g,1} \\
\vdots
\\ \varepsilon_{g,n_g}\end{array}\right)
\]</span></p>
</div>
<div id="least-squares-estimates-for-the-one-way-anova-model" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Least squares estimates for the one-way ANOVA model<a href="qualitative-independent-variables.html#least-squares-estimates-for-the-one-way-anova-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have written the model in matrix notation, we can
immediately obtain least squares estimates for the unknown group
means <span class="math inline">\(\mu_1,\ldots,\mu_g\)</span>, using the formula
<span class="math inline">\(\hat{\boldsymbol{\beta}}=(X^TX)^{-1}X^T\mathbf{y}\)</span>. Since
<span class="math display">\[
(X^TX)^{-1}=\left(\begin{array}{cccc}n_1 &amp; 0 &amp;  \ldots &amp; 0 \\ 0 &amp;
n_2  &amp; \ldots &amp; 0 \\ \vdots &amp; &amp; \ddots &amp;   \vdots \\ 0 &amp; 0 &amp; \ldots
&amp; n_g \end{array} \right)^{-1},\quad
X^T\mathbf{y}=\left(\begin{array}{c} \sum_{j=1}^{n_1} y_{1,j} \\ \vdots \\
\sum_{j=1}^{n_g} y_{g,j} \end{array}\right)
\]</span>
we have
<span class="math display">\[
\hat{\boldsymbol{\beta}}=\left(\begin{array}{c}\hat{\mu}_1 \\ \vdots \\ \hat{\mu}_g \end{array}\right) = \left(\begin{array}{c} \frac{1}{n_1} \sum_{j=1}^{n_1} y_{1,j} \\ \vdots \\
\frac{1}{n_g} \sum_{j=1}^{n_g} y_{g,j} \end{array}\right)
\]</span>
This result is intuitive. For
example, in group 1 we have <span class="math inline">\(n_1\)</span> observations
<span class="math inline">\(y_{1,1},\ldots,y_{1,n_1}\)</span>, all with expected value <span class="math inline">\(\mu_1\)</span>. The
obvious estimate for <span class="math inline">\(\mu_1\)</span> is the sample mean <span class="math inline">\(\frac{1}{n_1} \sum_{j=1}^{n_1} y_{1,j}\)</span>.</p>
</div>
<div id="fitting-a-one-way-anova-model-in-r" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Fitting a one-way ANOVA model in R<a href="qualitative-independent-variables.html#fitting-a-one-way-anova-model-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We fit the model
<span class="math display">\[ Y_{ij}=\mu_i + \varepsilon_{ij},\]</span>
for <span class="math inline">\(i=1,\ldots,g\)</span>, <span class="math inline">\(j=1,\ldots,n_i\)</span> to the cancer data as follows.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="qualitative-independent-variables.html#cb36-1" aria-hidden="true" tabindex="-1"></a>lmCancer <span class="ot">&lt;-</span> <span class="fu">lm</span>(survival <span class="sc">~</span> organ <span class="sc">-</span> <span class="dv">1</span>, cancer)</span></code></pre></div>
<p>(the reason for the <code>- 1</code> in the formula will become clearer shortly, when we look at an alternative parametrisation of the model.)</p>
<p>We can now use the <code>summary()</code> command to get the parameter estimates</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="qualitative-independent-variables.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmCancer)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = survival ~ organ - 1, data = cancer)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1371.91  -241.75  -111.50    87.19  2412.09 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## organBreast     1395.9      201.9   6.915 3.77e-09 ***
## organBronchus    211.6      162.4   1.303  0.19764    
## organColon       457.4      162.4   2.817  0.00659 ** 
## organOvary       884.3      273.3   3.235  0.00199 ** 
## organStomach     286.0      185.7   1.540  0.12887    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 669.5 on 59 degrees of freedom
## Multiple R-squared:  0.5437, Adjusted R-squared:  0.505 
## F-statistic: 14.06 on 5 and 59 DF,  p-value: 4.766e-09</code></pre>
<p>We have <span class="math inline">\(\hat{\beta}_1 = 1395.9\)</span>, <span class="math inline">\(\hat{\beta}_2 = 211.6\)</span> and so on.</p>
<p>Note that this model does not have an intercept, so the <code>F-statstic</code> and <code>p-value</code> in the last line report a hypothesis test of <span class="math inline">\(H_0: \beta_i = 0\)</span> for <span class="math inline">\(i=1,\ldots,5\)</span>, with <span class="math inline">\(H_A:\beta_i \neq 0\)</span> for at least one <span class="math inline">\(i\)</span>.</p>
</div>
<div id="an-alternative-parameterisation" class="section level2 hasAnchor" number="10.7">
<h2><span class="header-section-number">10.7</span> An alternative parameterisation<a href="qualitative-independent-variables.html#an-alternative-parameterisation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>None of the hypothesis tests in the <code>summary()</code> output above are likely to be of any interest; we are more likely to be interested in <em>differences</em> between groups, rather than whether some or all of the groups have a population mean response of 0.</p>
<p>An alternative way of writing the one-way ANOVA model is as follows:
<span class="math display">\[
Y_{i,j}=\mu + \tau_i + \varepsilon_{i,j},
\]</span>
for <span class="math inline">\(i=1,\ldots,g\)</span>, <span class="math inline">\(j=1,\ldots,n_i\)</span> and with <span class="math inline">\(\varepsilon_{i,j}\sim N(0,\sigma^2)\)</span>.</p>
<p>The <em>intention</em> of this parametrisation could be to think of <span class="math inline">\(\mu\)</span> as
the grand mean, and <span class="math inline">\(\tau_i\)</span> as the difference between the
mean of group <span class="math inline">\(i\)</span> and the grand mean <span class="math inline">\(\mu\)</span>. However, this model is <em>over-parametrised</em>.</p>
In matrix notation, we would write this as
<span class="math display">\[
\mathbf{Y} = X\boldsymbol{\beta} + \boldsymbol{\varepsilon},
\]</span>
with
<span class="math display">\[
\mathbf{Y}=\left(\begin{array}{c}Y_{1,1} \\ \vdots \\ Y_{1,n_1} \\ Y_{2,1}\\
\vdots \\ Y_{2,n_2} \\ \vdots \\ Y_{g,1} \\
\vdots
\\ Y_{g,n_g}\end{array}\right),\quad
X=\left(\begin{array}{cccccc}1&amp;1&amp; 0 &amp; 0  &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1&amp; 1&amp; 0 &amp; 0 &amp; \ldots &amp; 0 \\ 1 &amp; 0&amp; 1 &amp; 0  &amp; \ldots &amp; 0 \\ \vdots &amp;  \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1 &amp; 0&amp; 1 &amp; 0 &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\ 1 &amp; 0&amp; 0 &amp; 0  &amp; \ldots &amp; 1 \\ \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1 &amp; 0&amp; 0 &amp; 0 &amp; \ldots &amp; 1
\end{array}\right),\quad
\boldsymbol{\beta}=\left(\begin{array}{c}\mu \\\tau_1 \\ \vdots \\
\tau_g\end{array}\right),\quad
\boldsymbol{\varepsilon}=\left(\begin{array}{c}\varepsilon{1,1} \\ \vdots \\ \varepsilon{1,n_1} \\ \varepsilon{2,1}\\
\vdots \\ \varepsilon{2,n_2}  \\ \vdots  \\ \varepsilon{g,1} \\
\vdots
\\ \varepsilon{g,n_g}\end{array}\right).
\]</span>
For this particular design matrix <span class="math inline">\(X\)</span>, we find that
<span class="math display">\[
X^TX=\left(\begin{array}{ccccc}n &amp; n_1 &amp; n_2 &amp; \cdots &amp; n_g
\\ n_1 &amp; n_1 &amp; 0  &amp; \cdots &amp; 0\\ n_2 &amp; 0 &amp; n_2 &amp; \cdots &amp; 0 \\ \vdots &amp; \vdots &amp;\vdots &amp; \ddots &amp; \vdots \\ n_g &amp; 0 &amp; 0 &amp; \cdots &amp;
n_g
\end{array}\right).
\]</span>
The matrix <span class="math inline">\(X^TX\)</span> cannot be inverted, as <span class="math inline">\(\det(X^TX)=0\)</span> (the first
column is the sum of columns 2 to <span class="math inline">\(g+1\)</span>, noting that <span class="math inline">\(\sum_{i=1}^g n_i=n\)</span>). Hence it is not possible to obtain least squares parameter
estimates for this model, as we cannot evaluate the expression
<span class="math inline">\(\boldsymbol{\beta}=(X^TX)^{-1}X^T\mathbf{y}\)</span>. Intuitively, this makes sense as we are
trying to estimate <span class="math inline">\(g+1\)</span> parameters representing group means (<span class="math inline">\(\mu\)</span> and
<span class="math inline">\(\tau_1,\ldots,\tau_g\)</span>) with data from only <span class="math inline">\(g\)</span> groups.
<p>The solution is to apply constraints to the parameters. One
possibility is to state that <span class="math inline">\(\tau_1=0\)</span>, so that the
model can be written as
<span class="math display">\[
Y_{i,j}=\left\{\begin{array}{ll}\mu + \varepsilon_{1,j} &amp; \mbox{$i=1$,
$j=1,\ldots n_1$}\\ \mu + \tau_i + \varepsilon_{i,j} &amp; \mbox{$i=2,\ldots,g$,
$j=1,\ldots n_i$} \end{array}\right.
\]</span>
For this parametrisation, <span class="math inline">\(\mu\)</span> is interpreted as the (population)
mean for group 1, and <span class="math inline">\(\tau_i\)</span> gives the difference in means between
group <span class="math inline">\(i\)</span> and group 1, for <span class="math inline">\(i\neq 1\)</span>. The null hypothesis of no
difference between group means is written as
<span class="math display">\[
H_0:\tau_2=\ldots=\tau_g=0,
\]</span>
and any individual <span class="math inline">\(\tau_i=0\)</span> implies no difference in means between
groups <span class="math inline">\(i\)</span> and 1. This model is written in matrix form as
<span class="math display">\[
\mathbf{Y} = X\boldsymbol{\beta} + \boldsymbol{\varepsilon},
\]</span>
with
<span class="math display">\[
\mathbf{Y}=\left(\begin{array}{c}Y_{1,1} \\ \vdots \\ Y_{1,n_1} \\ Y_{2,1}\\
\vdots \\ Y_{2,n_2}  \\ \vdots  \\ Y_{g,1} \\
\vdots
\\ Y_{g,n_g}\end{array}\right),\quad
X=\left(\begin{array}{ccccc}1&amp; 0 &amp; 0  &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1&amp; 0 &amp; 0 &amp; \ldots &amp; 0 \\ 1&amp; 1 &amp; 0  &amp; \ldots &amp; 0 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1&amp; 1 &amp; 0 &amp; \ldots &amp; 0 
\\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots   \\ 1&amp; 0 &amp; 0  &amp; \ldots &amp; 1 \\ \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots  \\
1&amp; 0 &amp; 0 &amp; \ldots &amp; 1
\end{array}\right),\quad
\boldsymbol{\beta}=\left(\begin{array}{c}\mu \\ \tau_2 \\ \vdots \\
\tau_g\end{array}\right),\quad
\boldsymbol{\varepsilon}=\left(\begin{array}{c}\varepsilon{1,1} \\ \vdots \\ \varepsilon{1,n_1} \\ \varepsilon{2,1}\\
\vdots \\ \varepsilon{2,n_2} \\ \vdots  \\ \varepsilon{g,1} \\
\vdots
\\ \varepsilon{g,n_g}\end{array}\right).
\]</span>
For this design matrix we find that
<span class="math display">\[
\hat{\boldsymbol{\beta}}=\left(\begin{array}{c}\frac{1}{n_1}\sum_{j=1}^{n_1} y_{1,j} \\
\frac{1}{n_2}\sum_{j=1}^{n_2} y_{2,j} -
\frac{1}{n_1}\sum_{j=1}^{n_1} y_{1,j} \\ \vdots \\
\frac{1}{n_g}\sum_{j=1}^{n_g} y_{g,j} -
\frac{1}{n_1}\sum_{j=1}^{n_1} y_{1,j}
\end{array}\right),
\]</span>
(details omitted), hence <span class="math inline">\(\hat{\mu}\)</span> is the sample mean of the
observations in group 1, and <span class="math inline">\(\hat{\tau}_i\)</span> is the difference
between the sample means of groups <span class="math inline">\(i\)</span> and 1.</p>
<p>This is actually the default parametrisation in R. If we leave out the <code>-1</code> from the previous command, we just do</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="qualitative-independent-variables.html#cb39-1" aria-hidden="true" tabindex="-1"></a>lmCancer <span class="ot">&lt;-</span> <span class="fu">lm</span>(survival <span class="sc">~</span> organ, cancer)</span></code></pre></div>
<p>and then use the <code>summary()</code> command as before.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="qualitative-independent-variables.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmCancer)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = survival ~ organ, data = cancer)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1371.91  -241.75  -111.50    87.19  2412.09 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     1395.9      201.9   6.915 3.77e-09 ***
## organBronchus  -1184.3      259.1  -4.571 2.53e-05 ***
## organColon      -938.5      259.1  -3.622 0.000608 ***
## organOvary      -511.6      339.8  -1.506 0.137526    
## organStomach   -1109.9      274.3  -4.046 0.000153 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 669.5 on 59 degrees of freedom
## Multiple R-squared:  0.3037, Adjusted R-squared:  0.2565 
## F-statistic: 6.433 on 4 and 59 DF,  p-value: 0.0002295</code></pre>
<p><code>(Intercept)</code> refers to <span class="math inline">\(\mu\)</span>. (So we can interpret the <code>-1</code> term in the formula argument as saying that we do <em>not</em> want an intercept.)</p>
<p>We have <span class="math inline">\(\hat{\mu} = 1395.9\)</span>, <span class="math inline">\(\hat{\tau}_2 = -1184.3,\ldots,\hat{\tau}_5 = -1109.9\)</span>.</p>
<p>Note that the <code>F-statistic</code> and <code>p-value</code> output now refer to a hypothesis test of
<span class="math display">\[
H_0: \tau_2 = \tau_3 = \tau_4 = \tau_5,
\]</span>
with the alternative that at least two <span class="math inline">\(\tau\)</span> parameters are not equal.</p>
<div class="example">
<p><span id="exm:exampleANOVA" class="example"><strong>Example 10.1  (Fitting a linear model in R: ANOVA.) </strong></span><br></p>
</div>
<p>Using R, fit a one-way ANOVA model to the built in data set <code>PlantGrowth</code>, using <code>weight</code> as the dependent variable. Type <code>?PlantGrowth</code> for details.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="qualitative-independent-variables.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(PlantGrowth)</span></code></pre></div>
<pre><code>##   weight group
## 1   4.17  ctrl
## 2   5.58  ctrl
## 3   5.18  ctrl
## 4   6.11  ctrl
## 5   4.50  ctrl
## 6   4.61  ctrl</code></pre>
<p>Obtain the parameter estimates, and comment on the <code>F-statistic</code> output from the <code>summary()</code> command. Use a suitable plot of the data to informally check your results.</p>
<div class="fold">
<p><strong>Solution</strong></p>
<p>The model is
<span class="math display">\[
Y_{ij} = \mu + \tau_i + \varepsilon_{ij},
\]</span>
where <span class="math inline">\(Y_{ij}\)</span> is the yield for the <span class="math inline">\(j\)</span>-th plant in treatment group <span class="math inline">\(i\)</span>, for <span class="math inline">\(i=1,2,3\)</span> and <span class="math inline">\(j=1,\ldots,10\)</span>. We set <span class="math inline">\(\tau_1=0\)</span> and assume <span class="math inline">\(\varepsilon_{ij}\sim N(0,\sigma^2)\)</span>.</p>
<p>We fit the model with the command</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="qualitative-independent-variables.html#cb44-1" aria-hidden="true" tabindex="-1"></a>lmPlant <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> group, PlantGrowth)</span></code></pre></div>
<p>and then do</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="qualitative-independent-variables.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmPlant)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ group, data = PlantGrowth)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0710 -0.4180 -0.0060  0.2627  1.3690 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.0320     0.1971  25.527   &lt;2e-16 ***
## grouptrt1    -0.3710     0.2788  -1.331   0.1944    
## grouptrt2     0.4940     0.2788   1.772   0.0877 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6234 on 27 degrees of freedom
## Multiple R-squared:  0.2641, Adjusted R-squared:  0.2096 
## F-statistic: 4.846 on 2 and 27 DF,  p-value: 0.01591</code></pre>
<p>From this we read off <span class="math inline">\(\hat{\mu}=5.0320\)</span>, <span class="math inline">\(\hat{\tau}_2=-0.3710\)</span>, <span class="math inline">\(\hat{\tau}_3=0.4940\)</span> and <span class="math inline">\(\hat{\sigma}=0.6234\)</span>.</p>
<p>From the <code>F-statistic</code> line, we see that the <code>p-value</code> is 0.01591. Hence there is moderately strong evidence against the hypothesis that <span class="math inline">\(\tau_2 = \tau_3 = 0\)</span>; moderately strong evidence against the hypothesis that all three groups have the same mean yield.</p>
<p>We can check these results informally using a box plot.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="qualitative-independent-variables.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(PlantGrowth, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> weight)) <span class="sc">+</span> </span>
<span id="cb47-2"><a href="qualitative-independent-variables.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="MAS5052-Part2_files/figure-html/unnamed-chunk-38-1.png" width="672" />
If we suppose that each group mean is approximately the same as the group median, then this confirms that</p>
<ol style="list-style-type: decimal">
<li><code>trt1</code> has the lowest mean (<span class="math inline">\(\hat{\tau}_2\)</span>) was negative;</li>
<li>although <span class="math inline">\(\tau_2\)</span> and <span class="math inline">\(\tau_3\)</span> may not be significantly different from 0 (<code>ctrl</code> and <code>trt1</code> have similar means; <code>ctrl</code> and <code>trt2</code> have similar means), it doesn’t not look plausible that all three groups have the same population mean (<code>trt1</code> and <code>trt2</code> look different).</li>
</ol>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="fitting-a-linear-model-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-independent-variables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
